### ISSUE TITLE
Spike: AssertionError when sending token

### ISSUE THREAD

**Issue by obiyankenobi** [HathorNetwork/hathor-core#100]
Discord user had this a few times. 

HathorWallet 0.11.3 on Windows

Wallet feedback
![image](https://user-images.githubusercontent.com/3236756/85959739-0ea2ba80-b996-11ea-9fca-b422fd4ba87a.png)

Server logs
```
2020-06-28 18:33:35 [critical ] [twisted]                                exc_info=(<class 'AssertionError'>, AssertionError(), <traceback object at 0x7fdc65ac6e08>)
2020-06-28 18:33:35 [info     ] [twisted] "172.17.0.3" - - [28/Jun/2020:18:33:35 +0000] "POST /v1a/thin_wallet/send_tokens HTTP/1.0" 500 9381 "-" "Mozilla/5.0 (Windows 
NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HathorWallet/0.11.3 Chrome/73.0.3683.121 Electron/5.0.7 Safari/537.36 HathorWallet/0.11.3"
```

**Comment by pedroferreira1** [comment]
I was testing this and trying to reproduce the error. I checkout to the version the user was using (v0.11.3) and did the test.

At first I saw two possible causes for the error, (i) sending a transaction with more than 255 inputs or (ii) sending a transaction with a reward locked output. In both cases we now have treatment but in this version we didn't have it.

Both tests worked fine (I received a response from the full node with the correct error).

For (i) I received 'Error parsing hexdump to create the transaction' and for (ii) 'Reward needs 300 blocks to be spent, 299 not enough'.

For a normal transaction it worked fine.

**Comment by obiyankenobi** [comment]
I think that for now we should only improve the logs to determine the cause of it.

**Comment by jansegre** [comment]
Most likely this does not apply anymore.
