### ISSUE TITLE
error grpc_tools.protoc and grpc_tools for pipenv run make protos

### ISSUE THREAD

**Issue by goodthebest** [HathorNetwork/hathor-core#101]
I'm install Hathor full node on Ubuntu 16.04 

To Generate grpc/protobuf modules:
`pipenv run make protos`
While running above suggested command, I am getting error, screen shot attached, I've even installed `python3 -m pip install --user grpcio-tools` still no avail. Please assist.

![image](https://user-images.githubusercontent.com/1715740/86010032-511ad480-ba34-11ea-9210-851dc638fa1c.png)

**Comment by jansegre** [comment]
Most `make` commands will require "dev-dependencies" that are only installed when you pass `--dev` to `pipenv install`. Could you try that and let me know how it goes?

**Comment by jansegre** [comment]
This issue has staled and the code has evolved a lot since then. Please reopen if this is still an issue for you.
