### ISSUE TITLE
Spike: Sync is taking longer and longer. Maybe something related to the number of peers.

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-core#115]

**Comment by pedroferreira1** [comment]
The beginning of May the full sync used to take around 1h and 10 minutes but we have ~10 peers on the network.

Did a full sync with full node version 0.36.1 and it took 3h and 10 minutes to finish. We have 20 peers on the network.

**Comment by jansegre** [comment]
This is no longer the case.
