### ISSUE TITLE
Disk space is increasing every day on node1

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-core#118]
![image](https://user-images.githubusercontent.com/3298774/87208380-e21b6680-c2e4-11ea-9ba1-42e1588595be.png)

**Comment by obiyankenobi** [comment]
I just deleted an old log file and it's back to 4.46gb. Still higher than node2

**Comment by obiyankenobi** [comment]
Not happening anymore. Also, node1 and node2 logs are about the same.
