### ISSUE TITLE
Make the storages resilient against sudden crashes

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-core#123]
With the new fast initialization we trust the data on storage, so it's important to make sure it won't have any problems with a sudden crash in the middle of a write.

**Comment by jansegre** [comment]
We aren't too resilient against sudden crashes in the recovery sense, but the node is already protected against starting after an invalid storage that results from a sudden crash. The need for this resilience is very minimal, so I will close this for now.
