### ISSUE TITLE
Push tx API should be a POST but it's a GET

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-core#134]
Lib: https://github.com/HathorNetwork/hathor-wallet-lib/pull/92

We will need to support GET and POST for now, to keep compatibility but we should release a new wallet version using the POST by default.

We are having problems with big transactions using GET.

**Comment by pedroferreira1** [comment]
We already have a POST endpoint for `push_tx`, however we are keeping also the GET endpoint for compatibility reasons.

**Comment by jansegre** [comment]
This should have been closed before.
