### ISSUE TITLE
DB snapshot to speed up syncing of new node deploys

### ISSUE THREAD

**Issue by jansegre** [HathorNetwork/hathor-core#143]
Related MR: https://gitlab.com/HathorNetwork/aws-deploy-tools/-/merge_requests/14

**Comment by obiyankenobi** [comment]
I think we have 2 goals with this:
 (i) start nodes faster;
(ii) reduce stress on the network when nodes are syncing;

The downside I see in this proposal is that it's very specific to AWS. There are currently 40 peers on the network and I think we (Hathor Labs) run less than 10. So this solution would only take care of (i), as any time someone starts a full node, it'd run a full sync.

**Comment by jansegre** [comment]
This is because this has to be specific to the deploy process. The alternative would be centralizing the distribution of blockchain, which I'm not comfortable at all with.

But I do think this helps with (ii), because we're the ones doing full syncs. I'm not really sure how the rest of the network is doing, but always doing full syncs is something specific to our deploy process, we don't force this process on anyone else.

If we are to improve the sync situation in general, I'd rather improve the sync protocol before considering centralizing the blockchain download.

**Comment by obiyankenobi** [comment]
I'm not sure we're the only ones doing full syncs. I got this image from mainnet 0.37.0, Aug 19th. This is our private full node, not serving any API:
![image](https://user-images.githubusercontent.com/3236756/92795607-6acb8700-f3a8-11ea-85e4-75b4bd18d13c.png)

Two full nodes connected to the network and it caused a spike on CPU usage. I don't believe this was us, because mainnet 0.37.1 was launched only this month. Unless it was some test some of us was doing, but it doesn't make much sense to start 2 full nodes.

Also, I wouldn't say we'd be centralizing the distribution of blockchain. We should have cli flags so anyone can start with the data they already have available or do a full sync. It's their choice.

I agree improving our sync protocol is something we need to do, but I'm not sure when we'll be able to allocate time to it. This solution would only be buying us time.

**Comment by jansegre** [comment]
> I'm not sure we're the only ones doing full syncs. I got this image from mainnet 0.37.0, Aug 19th. This is our private full node, not serving any API:
> ![image](https://user-images.githubusercontent.com/3236756/92795607-6acb8700-f3a8-11ea-85e4-75b4bd18d13c.png)
> 
> Two full nodes connected to the network and it caused a spike on CPU usage. I don't believe this was us, because mainnet 0.37.1 was launched only this month. Unless it was some test some of us was doing, but it doesn't make much sense to start 2 full nodes.
> 
> Also, I wouldn't say we'd be centralizing the distribution of blockchain. We should have cli flags so anyone can start with the data they already have available or do a full sync. It's their choice.

But then this change is almost meaningless. If they wanted to do a full sync, they can. And it might still be the recommended way to start. It might be better not to trust our distributed metadata (or not to include any metadata), which would lead to a slow start, which is nearly as fast as a full sync, but with more attack opportunities. So that's why I'd argue a full sync to be the default.

> I agree improving our sync protocol is something we need to do, but I'm not sure when we'll be able to allocate time to it. This solution would only be buying us time.

Yeah, I agree. But to me this is still something particular of how our deployment is setup. I've helped some people setup their deployment in a way that does not have this problem, and that should be the default. So that's why I think it isn't worth designing something built-in the fullnode, which also would require some maintenance and high level of attention and security protections that would take some valuable time.

**Comment by pedroferreira1** [comment]
For me this is a good solution. Even though I agree with the downside, I see as a good and fast solution for what we wanted to do (update our full node with new code faster).

> But I do think this helps with (ii), because we're the ones doing full syncs. I'm not really sure how the rest of the network is doing, but always doing full syncs is something specific to our deploy process, we don't force this process on anyone else.

I think I understand this sentence as we are the only peers that do a full sync every time we need to update the full node. The only peers doing a full sync are the new ones in the network but they don't do a full sync when update the version.

And as @jansegre said, people running a new full node should not trust our snapshot, they should do a full sync in the network even if there is faster way available.

**Comment by obiyankenobi** [comment]
Ok, I agree that this is a good solution for us now.

**Comment by msbrogli** [comment]
I prefer to store the snapshot in S3. We could use it for different things, such as getting our local nodes synced faster to collect statistics or check whether a PR will cause hard fork or not.

**Comment by msbrogli** [comment]
Or we could distribute it using a torrent, just like many blockchains do. But I don't think we need it now.

**Comment by obiyankenobi** [comment]
> to collect statistics or check whether a PR will cause hard fork or not.

We can also upload it to S3 whenever we create a new snapshot so we use it in these development/test scenarios.

**Comment by jansegre** [comment]
> I prefer to store the snapshot in S3. We could use it for different things, such as getting our local nodes synced faster to collect statistics or check whether a PR will cause hard fork or not.

I agree having it on S3 is more generally usable. But that's the only benefit, and we don't have any plans to use it, versus the disadvantage of having a more complicated deploy process (at least it isn't immediately obvious how I would alter our current deploy process to use it).

I'd rather stick to my proposal and later we can design an update process that stores the "source" database no S3 that will get copied to a volume snapshot that the deploy process will use.
