### ISSUE TITLE
504 error when sending transaction

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-core#145]
Two users have reported that they received a 504 error when sending a transaction. The tx is sent and propagated but the request returns with an error.

One of the possible reasons might be an "Unhandled deferred error" that sometimes appears in the server logs after a tx is sent but has to be further investigated.

![image](https://user-images.githubusercontent.com/3298774/92858328-500b0980-f3cc-11ea-969c-9b7854b0fa7b.png)

**Comment by jansegre** [comment]
We haven't had any reports like this for a long while now.
