### ISSUE TITLE
Testnet is not mining blocks

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-core#174]
Last block was on Dec 25th (https://explorer.foxtrot.hathor.network/transaction/00000000001b7e0468b100afdf9198a49a587b97e8379c7626b8f32890fdbd4f)

We've changed how blocks are mined ~Dec 17th when we merged this PR (https://github.com/HathorNetwork/tx-mining-service/pull/5). In order to have the testnet working with the newest wallet version, we had to start a tx mining service, so the testnet txs could be mined. Because of that we decided that we could have only one cpuminer to mine both txs and blocks and only connected to the tx mining service.

Testnet tx mining service: 18.219.106.108

In our log we are always getting error in `get_block_template` endpoint.

```
txstratum.manager - ERROR - 2021-01-07 10:36.52 Error updating block template  
Traceback (most recent call last):
  File "/home/ubuntu/tx-mining-service/txstratum/manager.py", line 136, in update_block_template
    block_template = await self.backend.get_block_template()
  File "/home/ubuntu/tx-mining-service/txstratum/commons/client.py", line 80, in get_block_template
    data = await resp.json()
  File "/home/ubuntu/.local/share/virtualenvs/tx-mining-service-Gf_BnUum/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://node1.foxtrot.testnet.hathor.network/v1a/get_block_template')
Traceback (most recent call last):
  File "/home/ubuntu/tx-mining-service/txstratum/manager.py", line 136, in update_block_template
    block_template = await self.backend.get_block_template()
  File "/home/ubuntu/tx-mining-service/txstratum/commons/client.py", line 80, in get_block_template
    data = await resp.json()
  File "/home/ubuntu/.local/share/virtualenvs/tx-mining-service-Gf_BnUum/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://node1.foxtrot.testnet.hathor.network/v1a/get_block_template')
```

We already had this problem before but it was caused by a full node regression and fixed in this PR (https://github.com/HathorNetwork/hathor-core/pull/156/files)

**Comment by pedroferreira1** [comment]
Executing the exact same methods from the testnet tx mining service server works (running from `python` shell).

```
from txstratum.commons.client import HathorClient
import asyncio

x = HathorClient('https://node1.foxtrot.testnet.hathor.network')

loop = asyncio.get_event_loop()

loop.run_until_complete(x.start())
>>> loop.run_until_complete(x.get_block_template())
BlockTemplate(data=b'\x00\x00\x01\x00\x00\x19\x00\x00\x00\x00@5\x00\x00\x00\x00\x00\x00_\xe6g~\x03\x00\x00\x00\x00\x00\x1b~\x04h\xb1\x00\xaf\xdf\x91\x98\xa4\x9aX{\x97\xe87\x9cv&\xb8\xf3(\x90\xfd\xbdO\x00\xe2\xc3\xec\x82\xcd\\7iav\xb0p\xb8\xc9E\xe7\xb1\xe2\xbe\x7f\xc5TRT\x7f\x19\x0c\xa2\xf7\xf4\x97\x00\xcb\x9bZ\xb7\xe9\xea\xfaVk\xcd\x00\xed\xc3\xbd\x16\xfe\xd6\x13n&\xd18\xaf\xe5c\xaeq\xb4\xde]\xbb\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', height=392362)
```

**Comment by pedroferreira1** [comment]
The tx mining service always update the timestamp of the job, however because of the long time without blocks (we had an increase on the hash rate, then we didn't find any blocks for some hours), we had to mine blocks in the past, and it was impossible with tx mining service, because it was always updating the timestamp.

**Comment by jansegre** [comment]
Aside from that the tx-mining-service could use the new mining api (`/v1a/mining_ws`) that includes the min and max timestamp that can be used, particularly the max timestamp would have prevented the issue that happened.

**Comment by msbrogli** [comment]
A solution is under review in [this PR](https://github.com/HathorNetwork/tx-mining-service/pull/11).

**Comment by msbrogli** [comment]
The problem was solved when it was detected by a hotfix. The hotfix was improved and became [this PR](https://github.com/HathorNetwork/tx-mining-service/pull/11). So, I'll just close this issue.
