### ISSUE TITLE
specify the change address?

### ISSUE THREAD

**Issue by viteshan** [HathorNetwork/hathor-core#179]
https://github.com/HathorNetwork/hathor-core/blob/1350f21ae4e2e381629756174275b29f6d163962/hathor/wallet/base_wallet.py#L413

I noticed that the change address is an unused address, can I specify the change address?

**Comment by pedroferreira1** [comment]
@viteshan it's not possible to specify the change address for now. It's something we've heard it would be good to have and we will eventually add support for that in our wallets.

Do you mind sharing your use case for that? I could help you with the best approach for your situation. You can get in touch with me through Discord if you prefer.

**Comment by viteshan** [comment]
as an exchange recharge wallet, each user generates an address from this wallet. and each pooling will generate an new address, which causes the wallet to have many addresses in a short time.

**Comment by jansegre** [comment]
This feature itself is still something good to have, but the built-in wallets are likely to be removed or used only for tests. The headless-wallet and such can implement this independently, so this isn't something that hathor-core has to support.
