### ISSUE TITLE
[Design] Well defined status API for sync-v1 and sync-v2 connections

### ISSUE THREAD

**Issue by jansegre** [HathorNetwork/hathor-core#186]
Currently the status API's `.connections.connected_peers` will have entries like:

```
{
  "id": "1f8bd99b5a7475cfffd8d03ad703c1ac3b4a8d1d2b63eb47f3c731a2e4e9635b",
  "app_version": "Hathor v0.38.0",
  "uptime": 12480454.660698414,
  "address": "3.238.33.245:54346",
  "state": "READY",
  "last_message": 0.005758762359619141,
  "plugins": {
    "node-sync-timestamp": {
      "latest_timestamp": 1615314942,
      "synced_timestamp": 1615314942
    }
  },
  "warning_flags": []
}
```

Sync information is extracted from `.plugins.node-sync-timestamp`.

With the introduction of `sync-v2`, there will be a different plugin with a different set of information that is specific to the new protocol.

I propose we add a simple `sync` attribute that is generic enough to be implemented by `sync-v1` and `sync-v2`, and has useful information for the explorer to use.

My initial proposal would look like this:

```
{
  "id": "1f8bd99b5a7475cfffd8d03ad703c1ac3b4a8d1d2b63eb47f3c731a2e4e9635b",
  "app_version": "Hathor v0.38.0",
  "uptime": 12480454.660698414,
  "address": "3.238.33.245:54346",
  "state": "READY",
  "last_message": 0.005758762359619141,
  "sync": {
    "state": "in-sync",
    "progress": 1.0,
  },
  "plugins": {
    "node-sync-timestamp": {
      "latest_timestamp": 1615314942,
      "synced_timestamp": 1615314942
    }
  },
  "warning_flags": []
}
```

The `sync` attributes are:

- `state`: can be `behind`, `in-sync`, `ahead`, to indicate where a peer state is in relation to us
- `progress`: float in the range `[0.0, 1.0]` that indicates the relative progress of the peer's sync in relation to us (a `in-sync` and `ahead` peers will always have progress `1.0`)

This approach aims to make it possible to display useful sync information that is algorithm-agnostic and still retain a place for algorithm-specific information.

Changes to the explorer should only be internal, and at most make information extracted from `.plugins.node-sync-timestamp` optional.

A future design should outline the specific fields of the sync-v2 plugin and how the explorer show present such information, which will be optional (that way any future update to the sync protocol will be backwards compatible).

How to calculate `sync.progress`:

- on `sync-v1`: `min(1.0, (peer.synced_timestamp - genesis_block.timestamp) / (my.latest_timestamp - genesis_block.timestamp))`;
- on `sync-v2`: `min(1.0, best_common_block_height / my.best_block_height)` (this is might change if we relay information about the progress of individual checkpoint sections to other peers, currently we don't).

**Comment by jansegre** [comment]
I thought about including an `eta` attribute, but I don't really think the fullnode should have to calculate an estimate for when the sync will finish, which can get very complex very quickly.

**Comment by thr0wn** [comment]
Approved.

**Comment by pedroferreira1** [comment]
> I thought about including an eta attribute, but I don't really think the fullnode should have to calculate an estimate for when the sync will finish, which can get very complex very quickly.

I agree with you. For me it's also approved.

**Comment by msbrogli** [comment]
@jansegre I like your proposal, but we still need to give more details of how to calculate the `sync.progress` for both sync-v1 and sync-v2.

**Comment by jansegre** [comment]
> @jansegre I like your proposal, but we still need to give more details of how to calculate the `sync.progress` for both sync-v1 and sync-v2.

I edited these calculation details, what do you think? @msbrogli

**Comment by msbrogli** [comment]
Approved.
