### ISSUE TITLE
Either remove the structure of a transaction from protobuf or use it for serialization

### ISSUE THREAD

**Issue by obiyankenobi** [HathorNetwork/hathor-core#20]
By @msbrogli 

I don't see the benefits of using our own custom serialization format and also fully describing the transactions in protobuf.
I think we should go one way or the other. Either we use protobuf for internal communication, passing only the bytes of the serialized transaction, or we use it to fully serialize our transactions.
What would be the pros and cons of using protobuf?

**Comment by jansegre** [comment]
The protobuf description has been removed.
