### ISSUE TITLE
Is there any API about the block details? 

### ISSUE THREAD

**Issue by Wangmmx** [HathorNetwork/hathor-core#232]
I want to know some information related to the block, such as get the current block number, get the details of a certain block, get the transactions existing in a certain block, etc. In addition, if I don't use the wallet-api way, can I get this information?

**Comment by D45putspin** [comment]
not sure if this what you looking for, https://docs.hathor.network/#operation/transaction

**Comment by Wangmmx** [comment]
Thank you for your reply, but this is not exactly what I want
Is there no more API? I want to find an interface for direct query by block number instead of block hash

**Comment by Wangmmx** [comment]
Is there any other way? Get block details by block number, or is there a way to get block hash by block number?

**Comment by luislhl** [comment]
Hello, @Wangmmx 

I believe someone from the team already helped you through other channels, but I'll respond here in case someone have the same question in the future.

A new API was implemented and released in v0.40.0 to allow getting block details by its height in the chain.
The docs can be checked in https://docs.hathor.network/#operation/block.

**Comment by panfeilei** [comment]
I face the same problem，no way to access the transaction information through the block height.Have you solved it?

**Comment by luislhl** [comment]
@panfeilei , have you tried the `block_at_height` endpoint I linked in my previous message?

You can do something like:
```
$ curl "https://node1.mainnet.hathor.network/v1a/block_at_height?height=1599246"
{
    "success": true,
    "block": {
        "tx_id": "000000000000000088d0582bcb24fbc1dde569c261565843e60255ee09f985a9",
        "version": 3,
        "weight": 63.94839125984663,
        "timestamp": 1626408744,
        "is_voided": false,
        "inputs": [],
        "outputs": [
            {
                "value": 3200,
                "token_data": 0,
                "script": "dqkUvvH5uq9gHdiC9diG8H+o9qjUdBOIrA==",
                "decoded": {
                    "type": "P2PKH",
                    "address": "HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt",
                    "timelock": null
                },
                "token": "00",
                "spent_by": null
            }
        ],
        "parents": [
            "00000000000000001a8a7d137e9883f5021e2005e33c0c32ae6ccd4235282172",
            "00000042fb34c09b977a6031b2871d9a1f7af49490b0d2a47e63230ab0f449b5",
            "000002fc6eceed95e765996072a743cee6252b2066d715c34c2c4eee2901c01b"
        ],
        "height": 1599246
    }
}
```

Is this what you are looking for?

**Comment by luislhl** [comment]
I'm going to close this issue, but if anyone needs to further discuss something here, feel free to add more comments.
