### ISSUE TITLE
Offline way to create transaction?

### ISSUE THREAD

**Issue by Wangmmx** [HathorNetwork/hathor-core#235]
Hi, I want to build the transaction offline. Here are my steps:
1.build the unsigned tx
2.sign the unsigned hex
3.build the final tx
4. broadcast the final tx hex

And there are some params to prepare 
1.how can I build the unsigned one? I used the api of `create_tx` and get the hex_data, if I don't use it, how can I get the hex_data?
2.the sign function is not clear, can you please help me with the source code?
3.how can I add the signature to build the final tx 

that's all, I am looking forward to your reply

**Comment by msbrogli** [comment]
Hi @Wangmmx. I guess this gist might help you: https://gist.github.com/msbrogli/2a519553e7066c949333cd87f4e72f85

Let me know if you need any help.

**Comment by Wangmmx** [comment]
Ok thanks a lot!

**Comment by Wangmmx** [comment]
Thank you very much, that is an offline method to build the transaction body and broadcast it. 
But I need to use js to implement it in my project, so I need to redefine the structure of the Transaction and rewrite these methods. Thanks anyway

**Comment by msbrogli** [comment]
Hey @Wangmmx . You can use `@hathor/wallet-lib` available in Nodejs. All these methods already exists there.

**Comment by Wangmmx** [comment]
That's great, I'll try again

**Comment by Wangmmx** [comment]
Hi,  I installed the @hathor/wallet-lib, and tried to create a transaction like:
```
const Transaction = require('@hathor/wallet-lib').transaction;
const tx = new Transaction([input1], [output1, output2], {tokens: ['123']})

```

got an error:
`TypeError: Transaction is not a constructor`

and I found the constructor of Transaction was deleted in the latest version, how can create the transaction then?

**Comment by msbrogli** [comment]
@Wangmmx Minor mistake in your code. You need to load the `Transaction` (instead of `transaction`).

```
nodejs
const Transaction = require('@hathor/wallet-lib').Transaction;
const tx = new Transaction([input1], [output1, output2], {tokens: ['123']})
```

I just tested this one and it worked nicely.

**Comment by Wangmmx** [comment]
oh, I wrote it wrong, sorry :), I copied the code out and used it, this lib is really useful, thanks a lot

**Comment by Wangmmx** [comment]
oh, I wrote it wrong, sorry :), I copied the code out and used it, this lib is really useful, thanks a lot

**Comment by msbrogli** [comment]
Happy to help. Let us know if you have any other issue, ok?

**Comment by Wangmmx** [comment]
No problem, I continue to build offline transaction and sign it

**Comment by Wangmmx** [comment]
And where can I found the sign function? I have got the getDataToSign and signed it in my local test, how can I put the signature I got into the transaction?

**Comment by msbrogli** [comment]
@Wangmmx You can use the `createInputData(...)` method. Check it out here: https://github.com/HathorNetwork/hathor-wallet-lib/blob/master/src/transaction.js#L273-L288

Notice that it is in the `transaction` module (lowercase).

**Comment by msbrogli** [comment]
After you generate the input data, you have to update the input object (e.g. `tx.inputs[0].data = createInputData(...)`) and serialize the transaction again.

**Comment by Wangmmx** [comment]
Ok, I’ll try it now, thank you for your patience

**Comment by msbrogli** [comment]
No problem. Happy to help!

**Comment by Wangmmx** [comment]
I have successfully sent offline transaction on the testnet, share this good news with you, thank you very much for your help, and close this issue
https://explorer.testnet.hathor.network/transaction/1ec2aceeef9a7e80a9b6c2b6d97b98d22c2f0bb11dec031acc36acdef8e5b3b0
