### ISSUE TITLE
403 ERROR The request could not be satisfied

### ISSUE THREAD

**Issue by Wangmmx** [HathorNetwork/hathor-core#239]
When calling the api, I got the 403 Error all the time:
```
{ StatusCodeError: 403 - "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>403 ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n<HR noshade size=\"1px\">\nBad request.\nWe can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n<BR clear=\"all\">\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n<BR clear=\"all\">\n<HR noshade size=\"1px\">\n<PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: UaHXqXoHcc9ltGz5xQN5VFEBaJghxr6iCQeUZxHOr1STWqDS3ENqTQ==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>"
```

But use testnet external node:
`https://node1.foxtrot.testnet.hathor.network/v1a/version` it is worked and returned the correct result
```
{
    "version": "0.39.1",
    "network": "testnet-foxtrot",
    "min_weight": 8,
    "min_tx_weight": 8,
    "min_tx_weight_coefficient": 0,
    "min_tx_weight_k": 0,
    "token_deposit_percentage": 0.01,
    "reward_spend_min_blocks": 300,
    "max_number_inputs": 255,
    "max_number_outputs": 255
}
```

use the mainnet external node
`https://node.explorer.hathor.network/v1a/version`
it got the 403 ERROR, I want to ask what can I do? Thanks a lot

**Comment by pedroferreira1** [comment]
Hi @Wangmmx, I've just tested and it's returning the correct expected response:

```
❯ curl https://node.explorer.hathor.network/v1a/version
{
    "version": "0.39.1",
    "network": "mainnet",
    "min_weight": 14,
    "min_tx_weight": 14,
    "min_tx_weight_coefficient": 1.6,
    "min_tx_weight_k": 100,
    "token_deposit_percentage": 0.01,
    "reward_spend_min_blocks": 300,
    "max_number_inputs": 255,
    "max_number_outputs": 255
}
```

Can you give me more details on how you are calling the API?

**Comment by Wangmmx** [comment]
Sorry for late
yes, this is my code:

```
var request = require('request-promise');
// const url = 'https://node.explorer.hathor.network/v1a/';
const url = 'https://node1.foxtrot.testnet.hathor.network/v1a/';
const path = 'version';
const method = 'GET';
const headers= { 'content-type': 'application/json' };
const params = {};

return request({method: method, url:url + path, headers: headers, body: params, json: true })
    .then(function (result) {
        console.log('result', result)
        return result
    })
    .catch(function (e) {
        throw e
    })

```

when changing the url to mainnet, it got error

**Comment by Wangmmx** [comment]
Can you please take a look for me, thanks

**Comment by msbrogli** [comment]
Hi @Wangmmx. It is weird that your code worked fine here. As we have rate limit for our public APIs, maybe you've reached it while testing. Can you try again, please?

```
$ node -v
v12.18.0
$ node test1.js
result {
  version: '0.39.1',
  network: 'testnet-foxtrot',
  min_weight: 8,
  min_tx_weight: 8,
  min_tx_weight_coefficient: 0,
  min_tx_weight_k: 0,
  token_deposit_percentage: 0.01,
  reward_spend_min_blocks: 300,
  max_number_inputs: 255,
  max_number_outputs: 255
}
```

**Comment by Wangmmx** [comment]
Yes of course,
for testnet is still fine
and the mainnet:
![Uploading image.png…]()

**Comment by Wangmmx** [comment]
I thought it was a problem with the authority of the mainnet, so I set up a node and contacted you about adding peerId to the whitelist. There should be no whitelisting yet. I'm not sure if this is the problem.

**Comment by msbrogli** [comment]
I just tested and got the same error as you did. I'll investigate and get back to you here.

**Comment by msbrogli** [comment]
@Wangmmx Our mainnet API is running below a CDN and the CDN is rejecting your request because you're sending a body content in a GET request. If you just remove the `body: params` from your call to `request(...)`, it works fine. Or you can set `const params = undefined;`.

Your request to the testnet worked because it goes straight to the load balancer which does not do this validation (and neither does our full-node).

**Comment by Wangmmx** [comment]
Thank you so much! I succeeded in doing what you said, and finally solved the problem, thank you for your patience

**Comment by Wangmmx** [comment]
and close this one
