### ISSUE TITLE
Tx Mining problem

### ISSUE THREAD

**Issue by Wangmmx** [HathorNetwork/hathor-core#247]
I built the transaction and then send to the mining service, when the job status is done, set the tx params and then push tx to the chain, but it is failed either, here is my code

```

const tx = new Transaction([input], [output1,output2]);
const getDataToSignHash = tx.getDataToSignHash();
const hash = Buffer.from(getDataToSignHash.toString('hex'), 'hex');

var sig = crypto.ECDSA.sign(hash, privateKeyA, 'little').set({
    nhashtype: crypto.Signature.SIGHASH_ALL
});
sig = sig.toDER();

var inputData = transaction.createInputData(sig, Buffer.from(sig.toString('hex'), 'hex'));

tx.inputs[0].data = inputData;

tx.weight = tx.calculateWeight();
tx.timestamp = Math.floor(Date.now()/ 1000);


var hex = tx.toBytes();


async function sendCoin1() {

    const url = 'https://txmining.testnet.hathor.network/';
    const method = 'POST';
    const path = 'submit-job';
    const headers= { 'content-type': 'application/json' };
    const params = {
        tx: hex.toString('hex'),
        propagate: false,
        add_parents: true
    };

    var jobId;
    return request({method: method, url:url + path, headers: headers, body: params, json: true })
        .then(function (result) {
            console.log('result', result)
            jobId = result.job_id;
            return jobId;
        }).catch(function (e) {
            throw e
        })
}



async function sendCoin2(jobId) {
   
        const url2 = 'https://txmining.testnet.hathor.network/job-status?job-id=';
        const method2 = 'GET';

        return request({method: method2, url:url2 + jobId})
            .then(function (result) {
                console.log('result', result);
   
                
                result = JSON.parse(result);
                console.log('status', result.status);

                if (result.status === 'done'){
                    tx.nonce = result.tx.nonce;
                    tx.weight = result.tx.weight;
                    tx.timestamp = result.tx.timestamp;
                    tx.parents = result.tx.parents;


                    console.log(JSON.stringify(tx));
                    var final = tx.toBytes();
                    console.log('final', final.toString('hex'));
                }

            })
            .catch(function (e) {
                throw e
            })
        
      
         
}


async function main() {
    var jobJd = await sendCoin1();
    console.log(jobJd)
    const sleep = (waitTimeInMs) => new Promise(resolve => setTimeout(resolve, waitTimeInMs));
    sleep(3000).then(() => {
        sendCoin2(jobJd);
    });
}

main();



```

**Comment by Wangmmx** [comment]
@msbrogli

**Comment by msbrogli** [comment]
Hi @Wangmmx. Can you share the tx bytes with me? There's something wrong with it and I'll find it out.

**Comment by Wangmmx** [comment]
Yes, I wrote down the tx bytes of hex string format:
000100010200a7d5261a8fce027e3a7a75a5cb31bc54ec53d15edce5d07349d9b143e5c4f801008e46304402203a16fc9eeec7baa8989d8bbd8b9001100b314c100b3fba7b7f844c96e4310f3f02201bcd9186cb3e66a2f5cf269a19d16f88c0601c8e79895d0b7c98a36f71ec8f2846304402203a16fc9eeec7baa8989d8bbd8b9001100b314c100b3fba7b7f844c96e4310f3f02201bcd9186cb3e66a2f5cf269a19d16f88c0601c8e79895d0b7c98a36f71ec8f280000000b00001976a914e9748aee0e77a9ba63611163ce8e453112ff599688ac00004e1500001976a914c50bfa2ba7efa29825dd3a07134c7cf2bca3022788ac4034081da9285ad160daaf57020000116b4a20bb48507613180a85133e11406369ad756ad56fbfeda9330eb5ae002dd983f2c6429493cc36a765b40da0a74b57334aa4e40aef2400bcc70cf3aa00000000

**Comment by msbrogli** [comment]
Thanks! I'm checking it out.

**Comment by msbrogli** [comment]
I tested here and it worked fine after I updated the timestamp (because it was too old).

#### Submit job
```
$ curl -v -X POST --data '{"tx": "'${TX_HEX}'"}' "https://txmining.testnet.hathor.network/submit-job"
{"job_id": "28ef34d59d59dd566e8a483cd2fbbde565e70add1175887f86f4e567c5a5bdff", "status": "mining", "message": "", "created_at": 1625209050.8186893, "tx": {"nonce": null, "parents": ["0000116b4a20bb48507613180a85133e11406369ad756ad56fbfeda9330eb5ae", "002dd983f2c6429493cc36a765b40da0a74b57334aa4e40aef2400bcc70cf3aa"], "timestamp": null, "weight": 20.031702587463602}, "timeout": 20.0, "submitted_at": null, "total_time": null, "expected_queue_time": 0, "expected_mining_time": 6.643741608848331, "expected_total_time": 6.643741608848331}
```

##### Check job status
```
$ curl -v "https://txmining.testnet.hathor.network/job-status?job-id=28ef34d59d59dd566e8a483cd2fbbde565e70add1175887f86f4e567c5a5bdff"
{"job_id": "28ef34d59d59dd566e8a483cd2fbbde565e70add1175887f86f4e567c5a5bdff", "status": "done", "message": "", "created_at": 1625209050.8186893, "tx": {"nonce": "0004686c", "parents": ["0000116b4a20bb48507613180a85133e11406369ad756ad56fbfeda9330eb5ae", "002dd983f2c6429493cc36a765b40da0a74b57334aa4e40aef2400bcc70cf3aa"], "timestamp": 1625209051, "weight": 20.031702587463602}, "timeout": 20.0, "submitted_at": 1625209052.4486682, "total_time": 1.629978895187378, "expected_queue_time": 0, "expected_mining_time": 6.643741608848331, "expected_total_time": 6.643741608848331}
```

**Comment by msbrogli** [comment]
I used hathor-core to parse the transaction and update the timestamp.

```python
In [1]: from hathor.transaction.base_transaction import tx_or_block_from_bytes

In [2]: tx_bytes = bytes.fromhex('000100010200a7d5261a8fce027e3a7a75a5cb31bc54ec53d15edce5d07349d9b143e5c4f801008e46304402203a16fc9eeec7baa8989d8bbd8b9001100b314c100b3fba7b7f844c96e4310f3f
   ...: 02201bcd9186cb3e66a2f5cf269a19d16f88c0601c8e79895d0b7c98a36f71ec8f2846304402203a16fc9eeec7baa8989d8bbd8b9001100b314c100b3fba7b7f844c96e4310f3f02201bcd9186cb3e66a2f5cf269a19d16f88c0
   ...: 601c8e79895d0b7c98a36f71ec8f280000000b00001976a914e9748aee0e77a9ba63611163ce8e453112ff599688ac00004e1500001976a914c50bfa2ba7efa29825dd3a07134c7cf2bca3022788ac4034081da9285ad160daaf
   ...: 57020000116b4a20bb48507613180a85133e11406369ad756ad56fbfeda9330eb5ae002dd983f2c6429493cc36a765b40da0a74b57334aa4e40aef2400bcc70cf3aa00000000')

In [3]: tx = tx_or_block_from_bytes(tx_bytes)

In [12]: import time

In [13]: tx.timestamp = int(time.time())

In [15]: bytes(tx).hex()
Out[15]: '000100010200a7d5261a8fce027e3a7a75a5cb31bc54ec53d15edce5d07349d9b143e5c4f801008e46304402203a16fc9eeec7baa8989d8bbd8b9001100b314c100b3fba7b7f844c96e4310f3f02201bcd9186cb3e66a2f5cf269a19d16f88c0601c8e79895d0b7c98a36f71ec8f2846304402203a16fc9eeec7baa8989d8bbd8b9001100b314c100b3fba7b7f844c96e4310f3f02201bcd9186cb3e66a2f5cf269a19d16f88c0601c8e79895d0b7c98a36f71ec8f280000000b00001976a914e9748aee0e77a9ba63611163ce8e453112ff599688ac00004e1500001976a914c50bfa2ba7efa29825dd3a07134c7cf2bca3022788ac4034081da9285ad160deb8a3020000116b4a20bb48507613180a85133e11406369ad756ad56fbfeda9330eb5ae002dd983f2c6429493cc36a765b40da0a74b57334aa4e40aef2400bcc70cf3aa00000000'
```

**Comment by Wangmmx** [comment]
Have you sent the tx to chain successfully? Yes, I build the tx and then submit job, it was all good, and check the job status, is fine too, but finally, when I push_tx, it reported the error

**Comment by msbrogli** [comment]
Oh! The problem was when submitting?

**Comment by msbrogli** [comment]
Let me try.

**Comment by Wangmmx** [comment]
Yes, at the time I checked job-status, wait it was done and set the params(timestamp, nonce ..etc)

and I use `push_tx`, it reported `  message: 'Failed to verify if elements are equal',
  can_force: true }`

when I change the timestamp , it changed `message: 'Transaction has invalid data (18332059465910239228681416254062703611103529083556222934557747009481983890405 < 108027803784545311754337236167909446549342735521936038117293293089849344)', can_force: true }`

**Comment by msbrogli** [comment]
It seems that your `inputs[0].data` does not solve the utxo's script. I'll parse it to see what's wrong.

**Comment by msbrogli** [comment]
When you change the timestamp, you have to mine the transaction again. That's why the error message is different.

**Comment by Wangmmx** [comment]
I just changed the timestamp to see what is different. Ok I still use mininng tx result directly, there is only one error then: `Failed to verify if elements are equal`,

Is my inputs[0].data something wrong?

**Comment by msbrogli** [comment]
> Is my inputs[0].data something wrong?

Yes. You are putting the same bytes for the pubkey and the signature. Check it out here:

```python
from hathor.transaction.base_transaction import tx_or_block_from_bytes
tx_bytes = bytes.fromhex('000100010200a7d5261a8fce027e3a7a75a5cb31bc54ec53d15edce5d07349d9b143e5c4f801008e46304402203a16fc9eeec7baa8989d8bbd8b9001100b314c100b3fba7b7f844c96e4310f3f02201bcd9186cb3e66a2f5cf269a19d16f88c0601c8e79895d0b7c98a36f71ec8f2846304402203a16fc9eeec7baa8989d8bbd8b9001100b314c100b3fba7b7f844c96e4310f3f02201bcd9186cb3e66a2f5cf269a19d16f88c0601c8e79895d0b7c98a36f71ec8f280000000b00001976a914e9748aee0e77a9ba63611163ce8e453112ff599688ac00004e1500001976a914c50bfa2ba7efa29825dd3a07134c7cf2bca3022788ac4034081da9285ad160daaf57020000116b4a20bb48507613180a85133e11406369ad756ad56fbfeda9330eb5ae002dd983f2c6429493cc36a765b40da0a74b57334aa4e40aef2400bcc70cf3aa00000000')
tx = tx_or_block_from_bytes(tx_bytes)

data = tx.inputs[0].data
n = data[0]
assert n <= 75
signature = data[1:1+n]
assert len(signature) == n
n2 = data[1+n]
assert n2 <= 75
pubkey = data[1+n+1:]
assert len(pubkey) == n2

print(pubkey == signature)
```

And it is printing `True`. They both have 70 bytes in total.

**Comment by Wangmmx** [comment]
I really can't think of how I did such a thing lol, I have successfully sent it before, maybe my hand slipped,  I'll check it first, thank you so much

**Comment by msbrogli** [comment]
No problem. It's happened to me several times as well. ;)

**Comment by Wangmmx** [comment]
I'll deal with it this error first, now it will report an error about my bitcore-lib dependency
maybe it has updated
`const OP_GREATERTHAN_TIMESTAMP = _bitcoreLib.util.buffer.hexToBuffer('6f');
                                                         ^
TypeError: _bitcoreLib.util.buffer.hexToBuffer is not a function`

**Comment by Wangmmx** [comment]
I tried again and it failed either :(
here is the tx:
000100010200a7d5261a8fce027e3a7a75a5cb31bc54ec53d15edce5d07349d9b143e5c4f8010069463044022033eba4cc8821e23a9ce23c7202e71f92302e1f9a27f4dcaf978e2b1d7e81ef8e022041dfa1addb49caf9279af2de011dd05039de5c82365e4f4c925b386c9e86eefc21035a27b3564c6a08337ba07f8120551d5721e9ae888bcd60df705de7509d2bc73d0000000200001976a914e9748aee0e77a9ba63611163ce8e453112ff599688ac00004e1e00001976a914c50bfa2ba7efa29825dd3a07134c7cf2bca3022788ac4033c1285e1b058760dedda102004d75c1edd4294379e7e5b7ab6c118c53c8b07a506728feb5688c8d26a97e5000e585e04ad770cfcc06c0976fe9089b4bf57570c96981e3ecd992ccafd2f2df00000000

**Comment by Wangmmx** [comment]
@jansegre could you please help me with this again? The tx bytes is above

**Comment by jansegre** [comment]
> @jansegre could you please help me with this again? The tx bytes is above

I checked your transaction with this script (this needs a hathor-core environment, will work directly on ipython):

```python
from hathor.transaction.base_transaction import tx_or_block_from_bytes
tx = tx_or_block_from_bytes(bytes.fromhex('000100010200a7d5261a8fce027e3a7a75a5cb31bc54ec53d15edce5d07349d9b143e5c4f8010069463044022033eba4cc8821e23a9ce23c7202e71f92302e1f9a27f4dcaf978e2b1d7e81ef8e022041dfa1addb49caf9279af2de011dd05039de5c82365e4f4c925b386c9e86eefc21035a27b3564c6a08337ba07f8120551d5721e9ae888bcd60df705de7509d2bc73d0000000200001976a914e9748aee0e77a9ba63611163ce8e453112ff599688ac00004e1e00001976a914c50bfa2ba7efa29825dd3a07134c7cf2bca3022788ac4033c1285e1b058760dedda102004d75c1edd4294379e7e5b7ab6c118c53c8b07a506728feb5688c8d26a97e5000e585e04ad770cfcc06c0976fe9089b4bf57570c96981e3ecd992ccafd2f2df00000000'))
tx.verify_without_storage()
```

And after that I get the following exception:

```
---------------------------------------------------------------------------
PowError                                  Traceback (most recent call last)
<ipython-input-10-947cd57dce0a> in <module>
----> 1 tx.verify_without_storage()

~/Projects/hathor-core4/hathor/transaction/transaction.py in verify_without_storage(self)
    328         """ Run all verifications that do not need a storage.
    329         """
--> 330         self.verify_pow()
    331         self.verify_number_of_inputs()
    332         self.verify_outputs()

~/Projects/hathor-core4/hathor/transaction/base_transaction.py in verify_pow(self, override_weight)
    599         minimum_target = self.get_target(override_weight)
    600         if numeric_hash >= minimum_target:
--> 601             raise PowError(f'Transaction has invalid data ({numeric_hash} < {minimum_target})')
    602 
    603     def verify_number_of_outputs(self) -> None:

PowError: Transaction has invalid data (67886225949285073819651610100596264219110929924298837578494775560505956499462 < 130910702846661339151077122386636916697291916674304973073876064550256640)
```

Which looks like it isn't mined (and in fact it isn't, the `nonce=0`) and the hash is `96163e046164aa3619b896f423f227914a3b945396f0c97ca5c09c97e8940006`.

So I tried mining it locally with `tx.start_mining()` and I get a `nonce=140953` (or `00022699` instead of `00000000` at the end). And now the hash is `000001d2599192089534910be88519fac039225a8b51d294d74cd6836491bf3b`.

I then tried making a full validation (this will need a working storage, thus has to run inside a working `hathor-cli shell ...`  (you can repeat the previous code), and it seems valid:

```python
tx.storage = tx_storage
tx.validate_full()  # -> True
```

**Comment by Wangmmx** [comment]
@jansegre Thank you for your willingness to reply to me first

The tx bytes is created by the steps of mining, and the code is all above, the nonce I got from minning service is 000ba47c instead of 0, Is it my assignment problem?
```  
                    tx.nonce = result.tx.nonce;
                    tx.weight = result.tx.weight;
                    tx.timestamp = result.tx.timestamp;
                    tx.parents = result.tx.parents;
```
And I have a complete log locally, the nonce is not 0. Or I can run it again and give you more data to check

**Comment by Wangmmx** [comment]
To added:
I tried agian and the tx bytes is
`000100010200a7d5261a8fce027e3a7a75a5cb31bc54ec53d15edce5d07349d9b143e5c4f8010069463044022033eba4cc8821e23a9ce23c7202e71f92302e1f9a27f4dcaf978e2b1d7e81ef8e022041dfa1addb49caf9279af2de011dd05039de5c82365e4f4c925b386c9e86eefc21035a27b3564c6a08337ba07f8120551d5721e9ae888bcd60df705de7509d2bc73d0000000200001976a914e9748aee0e77a9ba63611163ce8e453112ff599688ac00004e1e00001976a914c50bfa2ba7efa29825dd3a07134c7cf2bca3022788ac4033c1285e1b058760e7ba310200912d9aaf73792e9ce71fc9a193671f6bd567799a8ae73c96210636e190e633009ef3d0da09174088f4baf94c7a0378fa2d66cee3c72638f4eef5f0b7a5f97b00000000`

and the transaction is:
`{"inputs":[{"hash":"00a7d5261a8fce027e3a7a75a5cb31bc54ec53d15edce5d07349d9b143e5c4f8","index":1,"data":{"type":"Buffer","data":[70,48,68,2,32,51,235,164,204,136,33,226,58,156,226,60,114,2,231,31,146,48,46,31,154,39,244,220,175,151,142,43,29,126,129,239,142,2,32,65,223,161,173,219,73,202,249,39,154,242,222,1,29,208,80,57,222,92,130,54,94,79,76,146,91,56,108,158,134,238,252,33,3,90,39,179,86,76,106,8,51,123,160,127,129,32,85,29,87,33,233,174,136,139,205,96,223,112,93,231,80,157,43,199,61]}}],"outputs":[{"value":2,"address":{"base58":"WjxRw9oa35KtE4AmRisFe5nG3XaVXBegXc","network":{"name":"testnet","versionBytes":{"p2pkh":73,"p2sh":135},"bitcoreNetwork":{"name":"testnet","alias":"test","pubkeyhash":73,"privatekey":128,"scripthash":135,"xpubkey":76067358,"xprivkey":76066276,"networkMagic":{"type":"Buffer","data":[249,190,180,217]},"port":8333,"dnsSeeds":[]}}},"tokenData":0,"timelock":null},{"value":19998,"address":{"base58":"WgdvLumwLXuPVdKxXoTsYddAdSaZnPvn22","network":{"name":"testnet","versionBytes":{"p2pkh":73,"p2sh":135},"bitcoreNetwork":{"name":"testnet","alias":"test","pubkeyhash":73,"privatekey":128,"scripthash":135,"xpubkey":76067358,"xprivkey":76066276,"networkMagic":{"type":"Buffer","data":[249,190,180,217]},"port":8333,"dnsSeeds":[]}}},"tokenData":0,"timelock":null}],"version":1,"weight":19.754522210690563,"nonce":"000b7326","timestamp":1625799217,"parents":["00912d9aaf73792e9ce71fc9a193671f6bd567799a8ae73c96210636e190e633","009ef3d0da09174088f4baf94c7a0378fa2d66cee3c72638f4eef5f0b7a5f97b"],"tokens":[],"hash":null,"_dataToSignCache":{"type":"Buffer","data":[0,1,0,1,2,0,167,213,38,26,143,206,2,126,58,122,117,165,203,49,188,84,236,83,209,94,220,229,208,115,73,217,177,67,229,196,248,1,0,0,0,0,0,2,0,0,25,118,169,20,233,116,138,238,14,119,169,186,99,97,17,99,206,142,69,49,18,255,89,150,136,172,0,0,78,30,0,0,25,118,169,20,197,11,250,43,167,239,162,152,37,221,58,7,19,76,124,242,188,163,2,39,136,172]}}`

and error is:
`{ success: false,
  message:
   'Transaction has invalid data (72579787167082247152347517049257252260966937780049047220801544530589269938520 < 130910702846661339151077122386636916697291916674304973073876064550256640)',
  can_force: true }`


The whole log:

```
tx hex to be minned: 000100010200a7d5261a8fce027e3a7a75a5cb31bc54ec53d15edce5d07349d9b143e5c4f8010069463044022033eba4cc8821e23a9ce23c7202e71f92302e1f9a27f4dcaf978e2b1d7e81ef8e022041dfa1addb49caf9279af2de011dd05039de5c82365e4f4c925b386c9e86eefc21035a27b3564c6a08337ba07f8120551d5721e9ae888bcd60df705de7509d2bc73d0000000200001976a914e9748aee0e77a9ba63611163ce8e453112ff599688ac00004e1e00001976a914c50bfa2ba7efa29825dd3a07134c7cf2bca3022788ac4033c1285e1b058760e7ba2f0000000000
job submit: { job_id:
   '056a4f9eb5d1eb6218f9b60604b6505efb0b1932a361f05e83bd5722695b9c67',
  status: 'pending',
  message: '',
  created_at: 1625799216.6390986,
  tx:
   { nonce: null,
     parents: [],
     timestamp: null,
     weight: 19.754522210690563 },
  timeout: 20,
  submitted_at: null,
  total_time: null,
  expected_queue_time: 0,
  expected_mining_time: 6.810965251017828,
  expected_total_time: 6.810965251017828 }
  
job status result: {"job_id": "056a4f9eb5d1eb6218f9b60604b6505efb0b1932a361f05e83bd5722695b9c67", "status": "done", "message": "", "created_at": 1625799216.6390986, "tx": {"nonce": "000b7326", "parents": ["00912d9aaf73792e9ce71fc9a193671f6bd567799a8ae73c96210636e190e633", "009ef3d0da09174088f4baf94c7a0378fa2d66cee3c72638f4eef5f0b7a5f97b"], "timestamp": 1625799217, "weight": 19.754522210690563}, "timeout": 20.0, "submitted_at": 1625799219.2692306, "total_time": 2.630131959915161, "expected_queue_time": 0, "expected_mining_time": 6.810965251017828, "expected_total_time": 6.810965251017828}
tx:
{"inputs":[{"hash":"00a7d5261a8fce027e3a7a75a5cb31bc54ec53d15edce5d07349d9b143e5c4f8","index":1,"data":{"type":"Buffer","data":[70,48,68,2,32,51,235,164,204,136,33,226,58,156,226,60,114,2,231,31,146,48,46,31,154,39,244,220,175,151,142,43,29,126,129,239,142,2,32,65,223,161,173,219,73,202,249,39,154,242,222,1,29,208,80,57,222,92,130,54,94,79,76,146,91,56,108,158,134,238,252,33,3,90,39,179,86,76,106,8,51,123,160,127,129,32,85,29,87,33,233,174,136,139,205,96,223,112,93,231,80,157,43,199,61]}}],"outputs":[{"value":2,"address":{"base58":"WjxRw9oa35KtE4AmRisFe5nG3XaVXBegXc","network":{"name":"testnet","versionBytes":{"p2pkh":73,"p2sh":135},"bitcoreNetwork":{"name":"testnet","alias":"test","pubkeyhash":73,"privatekey":128,"scripthash":135,"xpubkey":76067358,"xprivkey":76066276,"networkMagic":{"type":"Buffer","data":[249,190,180,217]},"port":8333,"dnsSeeds":[]}}},"tokenData":0,"timelock":null},{"value":19998,"address":{"base58":"WgdvLumwLXuPVdKxXoTsYddAdSaZnPvn22","network":{"name":"testnet","versionBytes":{"p2pkh":73,"p2sh":135},"bitcoreNetwork":{"name":"testnet","alias":"test","pubkeyhash":73,"privatekey":128,"scripthash":135,"xpubkey":76067358,"xprivkey":76066276,"networkMagic":{"type":"Buffer","data":[249,190,180,217]},"port":8333,"dnsSeeds":[]}}},"tokenData":0,"timelock":null}],"version":1,"weight":19.754522210690563,"nonce":"000b7326","timestamp":1625799217,"parents":["00912d9aaf73792e9ce71fc9a193671f6bd567799a8ae73c96210636e190e633","009ef3d0da09174088f4baf94c7a0378fa2d66cee3c72638f4eef5f0b7a5f97b"],"tokens":[],"hash":null,"_dataToSignCache":{"type":"Buffer","data":[0,1,0,1,2,0,167,213,38,26,143,206,2,126,58,122,117,165,203,49,188,84,236,83,209,94,220,229,208,115,73,217,177,67,229,196,248,1,0,0,0,0,0,2,0,0,25,118,169,20,233,116,138,238,14,119,169,186,99,97,17,99,206,142,69,49,18,255,89,150,136,172,0,0,78,30,0,0,25,118,169,20,197,11,250,43,167,239,162,152,37,221,58,7,19,76,124,242,188,163,2,39,136,172]}}
tx bytes: 000100010200a7d5261a8fce027e3a7a75a5cb31bc54ec53d15edce5d07349d9b143e5c4f8010069463044022033eba4cc8821e23a9ce23c7202e71f92302e1f9a27f4dcaf978e2b1d7e81ef8e022041dfa1addb49caf9279af2de011dd05039de5c82365e4f4c925b386c9e86eefc21035a27b3564c6a08337ba07f8120551d5721e9ae888bcd60df705de7509d2bc73d0000000200001976a914e9748aee0e77a9ba63611163ce8e453112ff599688ac00004e1e00001976a914c50bfa2ba7efa29825dd3a07134c7cf2bca3022788ac4033c1285e1b058760e7ba310200912d9aaf73792e9ce71fc9a193671f6bd567799a8ae73c96210636e190e633009ef3d0da09174088f4baf94c7a0378fa2d66cee3c72638f4eef5f0b7a5f97b00000000

Process finished with exit code 0
```

**Comment by jansegre** [comment]
@Wangmmx I tested `000ba47c` and it is a valid nonce too (hash becomes `00000614820e4df08a4085493264677dc4ec7005c247792144a69c4d91f420b4`). But certainly somewhere in your steps the nonce was not updated.

Looking at the bytes of the transaction:

```
000100010200a7d5261a8fce027e3a7a75a5cb31bc54ec53d15edce5d07349d9b
143e5c4f8010069463044022033eba4cc8821e23a9ce23c7202e71f92302e1f9a
27f4dcaf978e2b1d7e81ef8e022041dfa1addb49caf9279af2de011dd05039de5
c82365e4f4c925b386c9e86eefc21035a27b3564c6a08337ba07f8120551d5721
e9ae888bcd60df705de7509d2bc73d0000000200001976a914e9748aee0e77a9b
a63611163ce8e453112ff599688ac00004e1e00001976a914c50bfa2ba7efa298
25dd3a07134c7cf2bca3022788ac4033c1285e1b058760e7ba310200912d9aaf7
3792e9ce71fc9a193671f6bd567799a8ae73c96210636e190e633009ef3d0da09
174088f4baf94c7a0378fa2d66cee3c72638f4eef5f0b7a5f97b00000000
```

It shouldn't be `...174088f4baf94c7a0378fa2d66cee3c72638f4eef5f0b7a5f97b00000000`, it should be `...174088f4baf94c7a0378fa2d66cee3c72638f4eef5f0b7a5f97b000ba47c` instead. When I test that, it validates successfully.

**Comment by jansegre** [comment]
> and error is:
> `{ success: false, message: 'Transaction has invalid data (72579787167082247152347517049257252260966937780049047220801544530589269938520 < 130910702846661339151077122386636916697291916674304973073876064550256640)', can_force: true }`

That message is _probably_ because it received a nonce=0, so the calculated hash isn't enough to pass the difficulty check. I mean probably because I get a different numerical hash using nonce=0 (those big numbers between `a < b`, when I test `b` is the same, but `a` is different):

```
PowError: Transaction has invalid data (67886225949285073819651610100596264219110929924298837578494775560505956499462 < 130910702846661339151077122386636916697291916674304973073876064550256640)
```

**Comment by Wangmmx** [comment]
Ok, I get it. I don't know why the nonce is not updated. I don't think there is a problem with my assignment, because the tx after I do the mining had nonce, but after using toBytes(), there is no nonce. I understand what you said, thank you very much, I will check the logic of toBytes()

**Comment by Wangmmx** [comment]
I got it! 
The nonce is not a string and I should convert it, or the toBytes() function can not serialize the nonce correctly.
And I sent it successfully :
https://explorer.testnet.hathor.network/transaction/00000617400510c24ecb6e60a7bab719cb6c509b7a092cffe0e75de6cb2dd198

Thanks all your help
@jansegre @msbrogli

**Comment by Wangmmx** [comment]
Close the issue now
