### ISSUE TITLE
How do I run and configure tx-minning-server? 

### ISSUE THREAD

**Issue by panfeilei** [HathorNetwork/hathor-core#266]
I send tx to tx-minning-server but the status is timeout，I don't know where I got it wrong

**Comment by msbrogli** [comment]
Hi @panfeilei . Can you share the transaction details here? And the http request and response as well, please.

**Comment by panfeilei** [comment]
> Hi @panfeilei . Can you share the transaction details here? And the http request and response as well, please.

![image](https://user-images.githubusercontent.com/11550198/126587125-2c99d3b5-2208-46b7-af3e-f6df6d3954a0.png)

**Comment by luislhl** [comment]
Hi @panfeilei , just found out about this issue.
Sorry for this time without response.

I hope you were able to solve this.

If not, or if you have any other issues regarding tx-mining-service, please ask in the https://github.com/HathorNetwork/tx-mining-service repository
