### ISSUE TITLE
Block API got the wrong data

### ISSUE THREAD

**Issue by Wangmmx** [HathorNetwork/hathor-core#267]
Hello, I found that the interface to get the block is unstable. When I change the height, the returned data does not change .Interface :/block_at_height?height=1599246

I change the height from 1599246 to 1599248 and got the same block

![image](https://user-images.githubusercontent.com/22836587/125913025-deb81ac7-b43e-4561-83c1-bdf6506f5293.png)

After a while, when I tried again, got the correct one,  I don't know if there is a cache or something.

**Comment by Wangmmx** [comment]
@msbrogli @jansegre

**Comment by msbrogli** [comment]
Hi @Wangmmx .

I couldn't replicate the issue here. I tested multiple times with different heights, and all tests were correct. I also tested in my browser (Google Chrome 91.0.4472.114) and it worked properly.

```
$ curl "https://node1.mainnet.hathor.network/v1a/block_at_height?height=1599246"
{
    "success": true,
    "block": {
        "tx_id": "000000000000000088d0582bcb24fbc1dde569c261565843e60255ee09f985a9",
        "version": 3,
        "weight": 63.94839125984663,
        "timestamp": 1626408744,
        "is_voided": false,
        "inputs": [],
        "outputs": [
            {
                "value": 3200,
                "token_data": 0,
                "script": "dqkUvvH5uq9gHdiC9diG8H+o9qjUdBOIrA==",
                "decoded": {
                    "type": "P2PKH",
                    "address": "HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt",
                    "timelock": null
                },
                "token": "00",
                "spent_by": null
            }
        ],
        "parents": [
            "00000000000000001a8a7d137e9883f5021e2005e33c0c32ae6ccd4235282172",
            "00000042fb34c09b977a6031b2871d9a1f7af49490b0d2a47e63230ab0f449b5",
            "000002fc6eceed95e765996072a743cee6252b2066d715c34c2c4eee2901c01b"
        ],
        "height": 1599246
    }
}
```

```
$ curl "https://node1.mainnet.hathor.network/v1a/block_at_height?height=1599248"
{
    "success": true,
    "block": {
        "tx_id": "0000000000000000e057b4209376d97ca33d4e23416be7f63c62793d54162f8f",
        "version": 3,
        "weight": 63.90355827053092,
        "timestamp": 1626408794,
        "is_voided": false,
        "inputs": [],
        "outputs": [
            {
                "value": 3200,
                "token_data": 0,
                "script": "dqkUvvH5uq9gHdiC9diG8H+o9qjUdBOIrA==",
                "decoded": {
                    "type": "P2PKH",
                    "address": "HPvkeYZMVrAJKWFj4oNhaSz8skVv5WveGt",
                    "timelock": null
                },
                "token": "00",
                "spent_by": null
            }
        ],
        "parents": [
            "000000000000000090a65cc08353998fcae18be77578d972d02319ed04cb0b3f",
            "00000042fb34c09b977a6031b2871d9a1f7af49490b0d2a47e63230ab0f449b5",
            "000002fc6eceed95e765996072a743cee6252b2066d715c34c2c4eee2901c01b"
        ],
        "height": 1599248
    }
}
```

**Comment by msbrogli** [comment]
@luislhl Any chance that we have a cache intermediary that is wrongly configured?

**Comment by luislhl** [comment]
@msbrogli , yes, indeed we had. But only in front of `node.explorer.hathor.network`, that's why you couldn't reproduce it when requesting to `node1.mainnet.hathor.network`.

I've fixed the problem in the cache configuration and it's working fine now.

Can you confirm it's working for you @Wangmmx ?
Thanks for the report, BTW.

**Comment by Wangmmx** [comment]
> @msbrogli , yes, indeed we had. But only in front of `node.explorer.hathor.network`, that's why you couldn't reproduce it when requesting to `node1.mainnet.hathor.network`.
> 
> I've fixed the problem in the cache configuration and it's working fine now.
> 
> Can you confirm it's working for you now @Wangmmx ?
> Thanks for the report, BTW.

It's working fine now. Thank you!
Yes I use node.explorer.hathor.network, I should try node1.mainnet.hathor.networ too, thanks anyway
@msbrogli @luislhl :)
