### ISSUE TITLE
rocksdb install problem on Windows 11

### ISSUE THREAD

**Issue by mbnunes** [HathorNetwork/hathor-core#316]
[ PT-BR ]
Prezados, só para comunicar, tentei instalar o hathor-core em um windows 11 utilizando as seguintes configurações:

Python3.6 - 3.7 - 3.8 e 3.9 
PowerShell e CMD
Visual Studio 2019

O poetry install -E rocksdb retorna esse erro no VS2019

[ENG]
Dear, just to communicate, I tried to install hathor-core on a windows 11 using the following settings:

Python3.6 - 3.7 - 3.8 and 3.9
PowerShell and CMD
Visual Studio 2019

Poetry install -E rocksdb returns this error in VS2019

`
      copying rocksdb\cpp\filter_policy_wrapper.hpp -> build\lib.win-amd64-3.7\rocksdb\cpp
      copying rocksdb\cpp\memtable_factories.hpp -> build\lib.win-amd64-3.7\rocksdb\cpp
      copying rocksdb\cpp\merge_operator_wrapper.hpp -> build\lib.win-amd64-3.7\rocksdb\cpp
      copying rocksdb\cpp\slice_transform_wrapper.hpp -> build\lib.win-amd64-3.7\rocksdb\cpp
      copying rocksdb\cpp\utils.hpp -> build\lib.win-amd64-3.7\rocksdb\cpp
      copying rocksdb\cpp\write_batch_iter_helper.hpp -> build\lib.win-amd64-3.7\rocksdb\cpp
      running build_ext
      skipping 'rocksdb\_rocksdb.cpp' Cython extension (up-to-date)
      building 'rocksdb._rocksdb' extension
      creating build\temp.win-amd64-3.7
      creating build\temp.win-amd64-3.7\Release
      creating build\temp.win-amd64-3.7\Release\rocksdb
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\mnune\AppData\Local\pypoetry\Cache\virtualenvs\hathor-RC0t7ej3-py3.7\include -IC:\Python37_64\include -IC:\Python37_64\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tprocksdb\_rocksdb.cpp /Fobuild\temp.win-amd64-3.7\Release\rocksdb\_rocksdb.obj -std=c++11 -O3 -Wall -Wextra -Wconversion -fno-strict-aliasing -fno-rtti
      cl : Linha de comando error D8021 : argumento numrico inv lido '/Wextra'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'C:\Users\mnune\AppData\Local\pypoetry\Cache\virtualenvs\hathor-RC0t7ej3-py3.7\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mnune\\AppData\\Local\\Temp\\pip-req-build-860bhwwv\\setup.py'"'"'; __file__='"'"'C:\\Users\\mnune\\AppData\\Local\\Temp\\pip-req-build-860bhwwv\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mnune\AppData\Local\Temp\pip-record-83lffxks\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\mnune\AppData\Local\pypoetry\Cache\virtualenvs\hathor-RC0t7ej3-py3.7\include\site\python3.7\python-rocksdb' Check the logs for full command output.

  at C:\Python37_64\lib\site-packages\poetry\utils\env.py:1180 in _run
      1176│                 output = subprocess.check_output(
      1177│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1178│                 )
      1179│         except CalledProcessError as e:
    → 1180│             raise EnvCommandError(e, input=input_)
      1181│
      1182│         return decode(output)
      1183│
      1184│     def execute(self, bin, *args, **kwargs):
`
[PT-BR]
Sem o rocksdb funciona lindamente, mas sem ele fica complicado.

[ENG]
Without rocksdb it works beautifully, but without it it's complicated.

**Comment by jansegre** [comment]
Currently we don't support to rocksdb on Windows. Be it Windows 10, 11 (7, XP, ...). Mainly because of two reasons:

- there aren't official builds of the rocksdb lib for Windows (and I've had endless problems trying to build it myself);
- the python binding we use doesn't build on Windows (we could fork that library if there was at least a reliable way to build the rocksdb lib).

Granted that it has been a while since I've revisited this. Also there has been no demand for running hathor-core _directly_ on Windows (it works well on WSL and Docker). So this is very low on our priority list.

**Comment by jansegre** [comment]
The minimal support we have on Windows is likely to be removed, so I'm closing this issue.
