### ISSUE TITLE
feature: reorg event on websocket api

### ISSUE THREAD

**Issue by andreabadesso** [HathorNetwork/hathor-core#328]
We currently have no event on the WebSocket that indicates that a reorg has happened, we have to detect it by checking if a block from the best chain is voided.

It would be nice to have an event that is emitted every time the fullnode detects a reorg, including information about the reorg, like the height of the first block that was voided (and the tx_id), our previous best block tx_id (that is now voided), the new best block tx_id, etc...

This would be used by the wallet-service daemon and by the network monitor I am currently working on

**Comment by jansegre** [comment]
The solution to this is using the "reliable events" websocket, which has explicit reorg events. The older websocket API should eventually be removed.
