### ISSUE TITLE
Coinbase maturity of 100 transactions

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-core#36]
Maybe we should require a minimum number of "confirmations" before allowing miners to spend their rewards, just like Bitcoin does [1].

- [1] https://bitcoin.stackexchange.com/questions/22548/coinbase-maturity-of-100-transactions

**Comment by obiyankenobi** [comment]
https://gitlab.com/HathorNetwork/hathor-python/merge_requests/340
