### ISSUE TITLE
is there a way to run this locally or make a new chain for this?

### ISSUE THREAD

**Issue by Smellyslab** [HathorNetwork/hathor-core#361]
i would love if we could make and run our own chains with this as im a python3 dev learning about crypto and blockchaind development, it would also allow us to test our own ideas and updates is this possible and / or allowed via hathors ToS and policies

**Comment by luislhl** [comment]
Yes, there is a guide which is probably what you are looking for: https://github.com/HathorNetwork/rfcs/blob/master/text/0033-private-network-guide.md

hathor-core licence is Apache 2.0, so yes, it allows modifications: https://github.com/HathorNetwork/hathor-core/blob/master/LICENSE.txt

If you need further help with this, you can reach out in our Discord server: https://hathor.network/community/
