### ISSUE TITLE
Stack with more than one element should be invalid

### ISSUE THREAD

**Issue by obiyankenobi** [HathorNetwork/hathor-core#39]
When processing the transaction (output script + input data), stack should be invalid if there's more than 1 item.

Item 6 in this BIP: https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki

**Comment by jansegre** [comment]
We already do this [here](https://github.com/HathorNetwork/hathor-core/blob/master/hathor/transaction/scripts/execute.py#L74-L88).
