### ISSUE TITLE
[Design] Index initialization skipping mechanism

### ISSUE THREAD

**Issue by jansegre** [HathorNetwork/hathor-core#396]
## Motivation

Currently we allow the mixing of rocksdb (persistent) storage with memory (not persistent) indexes, in addition to having optional indexes. We get around the problems this might have by simply always initializing all the indexes that were enabled, which means that indexes that should be persistent (rocksdb indexes) aren't, even though they are already stored in disk.

The main dilemma that comes from this is that consistency between the persisted database and the persisted indexes can drift whenever the fullnode is run with different parameters (currently these: `--x-rocksdb-indexes` and `--wallet-indexes` will affect this). Most commonly, rocksdb indexes aren't used by default (and we expect very few, if any, people are actually using it in production), so whenever it becomes on by default, the database will be complete, but the indexes will be empty, requiring an initialization of the indexes.

## Guide level explanation

The database will store the last time it initialized itself and each of the indexes. When a database is initialized, before the corresponding timestamps, it will check, when necessary, if the indexes need to be updated when that is the case they will be included in an initialization loop, which for now will always include the interval-trees indexes as they are always memory only.

## Reference level explanation

There will be a new attribute created per index, which are only going to be _effectively_ (more on this later) used on the rocksdb storage. These are:

- `database_last_init_timestamp`
- `*_index_init_timestamp` for each of: `tips_all, tips_block, tips_tx, sorted_all, sorted_block, sorted_tx, deps, height, mempool_tips, addresses, tokens`

A migration (a simple migration system was already created on one of the open PRs) will be used to create these timestamps, when this migration first runs it will either store the current timestamp on _all_ attributes if the database is fresh, or only the first attribute (`database_last_init_timestamp`) and leave the others zeroed as to force the indexes to be initialized.

The initialization of the indexes will happen in a single pass, of which the method to iterate can be chosen appropriately depending on what needs to be initialized (if sorted_all index is already initialized a faster iteration can be used). The "lone" interval-tree index will use the same loop, as it always has to be initialized.

The first step is resetting the timestamps to zero (because in case the rebuilding of indexes is interrupted we have to make sure to always update it on the following initialization). Then after the indexes have been rebuilt, we update the timestamp to the respective indexes timestamp to the same timestamp as `database_last_init_timestamp`.

## Alternatives

- Disallow using memory indexes with rocksdb storage and make optional wallet indexes permanent;
- Make the pairing of memory/rocksdb and option indexes "permanent" by storing it into the storage, and a different pairing would require a database reset (either from scratch or from a backup, we can provide different backups, or a "fit all" backup that once started can only be used with one set of options); *aside from the mechanism to restore from backup, this is already implemented on the "speed-up initialization dev branch", it's a good alternative, but maybe less user friendly

## Tasks

This design as it is, is probably not going to be split in multiple tasks, so it will be it's own task. The estimate is of 2 dev days.

**Comment by jansegre** [comment]
I think it would be ideal to get feedback from @msbrogli and @pedroferreira1 on this.

**Comment by msbrogli** [comment]
I understood the problem, and I agree we should fix it. I don't fully understood the proposed solution. Let me add a few questions that might help me to understand better:

1) When will each of these attributes be updated?

1a) database_last_init_timestamp
1b) main_indexes_last_init_timestamp
1c) optional_indexes_last_init_timestamp

2) Which indexes will belong to `main_indexes_last_init_timestamp` and which will belong to `optional_indexes_last_init_timestamp`?

3) Shouldn't we create one attribute per index? I mean, if we treat indexes separately, we can run even more complex scenarios where some are on memory and others are on disk.

**Comment by pedroferreira1** [comment]
> Shouldn't we create one attribute per index? I mean, if we treat indexes separately, we can run even more complex scenarios where some are on memory and others are on disk.

I agree with this, especially the `optional_indexes_last_init_timestamp`. We might create new optional indexes in the future, and we could have different scenarios where both optional indexes are chosen and also only one of them.

> When will each of these attributes be updated?

As far as I understood, once we finish loading the database and initializing the indexes.

Only one question, if we detect that the wallet index is outdated compared to the main indexes (i.e. we've run the full node with wallet index in the past, so we already have things there but the last time we ran without it), do we need to build the full index from zero, or can we just complete it?

**Comment by jansegre** [comment]
@msbrogli 

> 1) When will each of these attributes be updated?

I'added the following paragraph to clarify this:

>> The first step is resetting the timestamps to zero (because in case the rebuilding of indexes is interrupted we have to make sure to always update it on the following initialization). Then after the indexes have been rebuilt, we update the timestamp to the respective indexes timestamp to the same timestamp as `database_last_init_timestamp`.

> 2) Which indexes will belong to `main_indexes_last_init_timestamp` and which will belong to `optional_indexes_last_init_timestamp`?

I updated the design to include the list of indexes that would go on each one.

> 3) How do you detect you need a full reindexing based on these attributes?

I guess I did not write it once, haha. In my head I could've sworn I've written that. But basically the pseudo logic is:

```
if database_last_init_timestamp == 0:
    continue  # no migration needed
elif main_indexes_last_init_timestamp != database_last_init_timestamp:
    rebuild all indexes  # the iterator used is slower
elif optional_indexes_last_init_timestamp != database_last_init_timestamp:
    rebuild only optional indexes  # the iterator used is faster
```

> 4. Shouldn't we create one attribute per index? I mean, if we treat indexes separately, we can run even more complex scenarios where some are on memory and others are on disk.

I think that's a good alternative, but for now it's only going to be a lot of repeated attributes and extra logic to handle the currently impossible case of a few different combination of indexes de-syncing. But, if we only add these three attributes now, we can migrate in the future with no loss of information or consistency, that's mainly why I'm not worried about "agglomerating" them right now.

And about running even more complex scenarios, I surely hope we don't go that way, haha!

**Comment by jansegre** [comment]
@pedroferreira1

> Only one question, if we detect that the wallet index is outdated compared to the main indexes (i.e. we've run the full node with wallet index in the past, so we already have things there but the last time we ran without it), do we need to build the full index from zero, or can we just complete it?

Yes, we have to rebuild the index from scratch. This is mainly because there currently isn't an easy way to save a "checkpoint" to continue from it later, transactions can arrive out of order globally (as in, a reorg) and that makes the timestamp not enough to be used as a checkpoint. I believe it's not impossible to create a scheme that makes it so we don't have to reset the indexes in these cases, for example, we could store a "processing id number" for each tx/block which would give us a total ordering of the transactions in the same order that they were added to the storage, which could then be used to know when was the exact point that an index stopped being updated and continue from there, guaranteeing consistency. But this is way out of the scope of this design and will not be worth it IMO.

**Comment by msbrogli** [comment]
@jansegre Creating a "processing id number" is something we'll probably have to do for another project this quarter. It seems you might benefit from it.

Regarding using one attribute per index, I feel we can make indexes register to initialization. So we could automate most of the conditions. What do you think?

**Comment by jansegre** [comment]
> Creating a "processing id number" is something we'll probably have to do for another project this quarter. It seems you might benefit from it.

That would be great, but also the other way around IMO, when we have a "processing id number" we can consider improving the indexes initialization. But a "processing id number" is only scratching the surface, we'd probably also need something like "recording at which id's a void status flipped", or store all the events and use their monotonic ids.

> Regarding using one attribute per index, I feel we can make indexes register to initialization. So we could automate most of the conditions. What do you think?

I think that makes sense. I'll update the proposal with those changes.

**Comment by pedroferreira1** [comment]
> That would be great, but also the other way around IMO, when we have a "processing id number" we can consider improving the indexes initialization. But a "processing id number" is only scratching the surface, we'd probably also need something like "recording at which id's a void status flipped", or store all the events and use their monotonic ids.

I agree with that. I think we can move without this and rebuild the full index for now. We can have this implemented later, when needed.

**Comment by jansegre** [comment]
@msbrogli @pedroferreira1 I think we reached a consensus on the design, right? This is also what I'm already implementing and nearly done.

**Comment by pedroferreira1** [comment]
✅

**Comment by msbrogli** [comment]
Thanks for the update, @jansegre . It's approved for me.
