### ISSUE TITLE
how could you make your own blockchain with this? 

### ISSUE THREAD

**Issue by Smellyslab** [HathorNetwork/hathor-core#398]
how could you create a hard fork of this and start a whole knew chain? I want to build on this and make my own currency using this source code... so how could one go about doing this?

**Comment by luislhl** [comment]
> how could you create a hard fork of this and start a whole knew chain? I want to build on this and make my own currency using this source code... so how could one go about doing this?

Hey @Smellyslab 

Maybe you don't need to fork the project to do what you want, creating a token in our blockchain could be enough to create your currency. But I'll talk about both options below.

### By creating tokens

You could create tokens in our Mainnet to represent your currency. This way your tokens would be protected by the Mining Power in our Mainnet, which provides a hashrate usually higher than even some other older sha256d coins, like Bitcoin Cash. If you create your own independent blockchain, you would need to get mining power for it to provide security. 

The caveat here is that to create tokens, the protocol requires a deposit of 0.01 HTR for every 1.00 Token unit.

### By just running a independent blockchain

You can run your independent blockchain even with the same codebase, if you want to. A fork is not required.

I would say a fork only makes sense if you want to make significant changes to the code and take your project towards a different direction.

This guide could help you in running this independent network: https://github.com/HathorNetwork/rfcs/blob/master/text/0033-private-network-guide.md

You would probably want to change some aspect of your new blockchain, like the token symbol and name (From `HTR` to something else), the address version bytes, the genesis block and transactions, etc. These things are all configurable in https://github.com/HathorNetwork/hathor-core/blob/master/hathor/conf/settings.py
