### ISSUE TITLE
Fix send tokens, push tx, and decode tx resources

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-core#4]
**Expected behavior:**

Send tokens API to work with a creation token tx. (Also happens with push tx and decode tx API's for creation token txs)

**Actual behavior:**

Status code 500 returns.

**How to reproduce it (as minimally and precisely as possible):**

Run a wallet and try to create a token.

**Version (full node version, wallet version, app version):**

Full node dev branch 
https://gitlab.com/HathorNetwork/hathor-python/commit/5ea3ab5834f3d8fbe730b204f08f32f4d1769359

**Platform: output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows):**

Darwin Pedros-MacBook-Pro-2.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Full node URL (in case it makes sense):**

Localhost

**Comment by msbrogli** [comment]
This bug was caused by which Merge Request? It is important to make clear that it is not a bug in our current testnet. It is just part of the development of the new features.
