### ISSUE TITLE
feat: Retry fetching whitelists

### ISSUE THREAD

**Issue by tuliomir** [HathorNetwork/hathor-core#431]
This is an improvement upon #301 and depends on it.
When a request to fetch the whitelist fails, we should retry in regular intervals before triggering an alert. This should increase this feature's fault tolerance.

We should, for example, 
- fail, wait 1 sec, try again
- fail, wait 5 secs, try again
- fail, wait 10 secs, try again,
- fail, log error.

**Comment by jansegre** [comment]
Currently this is done on the alert handling side, I think that is acceptable.
