### ISSUE TITLE
[Low-Level Design] Built-in message broker for full-node events 

### ISSUE THREAD

**Issue by lucas3003** [HathorNetwork/hathor-core#437]
_This design has been moved and updated [here](https://github.com/HathorNetwork/rfcs/blob/master/projects/reliable-integration/0002-low-level-design.md)._

## Goal of this document

This low-level design intends to go deeper on the technical aspects of the project. If you want more abstract information, please consult the [high-level design](https://github.com/HathorNetwork/hathor-core/issues/405)

## Full-node execution

![Full-Node-Cycle drawio](https://user-images.githubusercontent.com/3287486/180022945-3938135d-e065-40f9-92f5-d1767bc5489a.png)

At first, when the full node is initiated, it moves to the `LOAD` state, where data is load from the database, without consulting the network. Once all local data is read, the full-node continuously sync with peers, changing to `SYNC` state.

In order to know which events will be triggered, we will store the states (`LOAD` and `SYNC`) as metadata. So, when the full node starts, we will check the metadata. If it is empty or `LOAD`, we do not know where it stopped and will emit all events. If it is `SYNC`, we will skip all event triggered during full node initialization until `LOAD_FINISHED`

## Flags

The following flags will be provided:

|Flag|Description|
|----|-----------|
|--enable-event-queue|Enable the message broker mechanism|

### Definition

An event is a data structure that captures a specific, atomic moment inside the node that might be useful for applications.

#### Event
```
{
    id: uint64, // Event order
    peer_id: string, // Full node UID, because different full nodes can have different sequences of events
    timestamp: float, // Timestamp in which the event was emitted. This will follow the unix_timestamp format
    type: enum, // One of the event types
    group_id: uint64, // Used to link events. For example, many TX_METADATA_CHANGED will have the same group_id when they belong to the same reorg process
    data: {}, // Variable for event type. Check Event Types section below
}
```

#### Metadata
```
{
   last_state: string // LOAD or SYNC
}
```

### Data Structures

```
tx_input: {
    value: int,
    token_data: int,
    script: string,
    index: int,
    tx_id: bytes,
}
```

```
tx_output: {
    value: int,
    script: bytes,
    token_data: int
}
```

```
token: {
    uid:  string,
    name: string,
    symbol: string
}
```

```
tx: {
    hash: string,
    nonce: int,
    timestamp: long,
    version: int,
    weight: float,
    inputs: tx_input[],
    outputs: tx_output[],
    parents: string[],
    tokens: token[],
    token_name: string,
    token_symbol: string,
    metadata: tx_metadata
}
```

```
spent_outputs: {
    spent_output: spent_output[]
}
```

```
spent_output: {
    index: int,
    tx_ids: string[]
}
```

```
tx_metadata: {
    hash: string,
    spent_outputs: spent_outputs[],
    conflict_with: string[]
    voided_by: string[]
    received_by: int[]
    children: string[]
    twins: string[]
    accumulated_weight: float
    score: float
    first_block: string or null
    height: int
    validation: string
}
```

```
tx_metadata_changed: {
    old_value: tx_metadata,
    new_value: tx_metadata
}
```

```
reorg: {
    reorg_size: int,
    previous_best_block: string, //hash of the block
    new_best_block: string //hash of the block
}
```

### Types

- LOAD_STARTED
- LOAD_FINISHED
- NEW_TX_ACCEPTED
- NEW_TX_VOIDED
- NEW_BEST_BLOCK_FOUND
- NEW_ORPHAN_BLOCK_FOUND
- REORG_STARTED
- REORG_FINISHED
- TX_METADATA_CHANGED
- BLOCK_METADATA_CHANGED

For a description of each event type, consult the `Event Types` section on the [the high level design](https://github.com/HathorNetwork/hathor-core/issues/405)

## Event capture

This is a diagram of the consensus algorithm, highlighting where each event will be triggered. ATTENTION: This is not a FULL diagram of the algorithm, but only with parts that are relevant to this design.

![Event-2 drawio](https://user-images.githubusercontent.com/3287486/180017941-eeafdd54-eefb-41f9-b281-9453a13e0212.png)

### Engine

RocksDB will be used to store the captured events. Along with the fact that we will not add a new dependency, it is a great engine to navigate through a key range. A seek takes O(log(n)), and each subsequent key is retrieved in O(1).

### Serialization

A new column-family will be created to store the events, so it stays decoupled from `tx` information.

Each event will be a `dict` on Python. To save the event, the whole `dict`object will be translated to a string using `json.dumps`. Then, it will be inserted on the database. The key will be the `event id`, which takes 8 bytes. All information will be stored using big-endian format.

### Deserialization

Each retrieved event from the database will be deserialized using `event.decode('utf-8')` and then `json.loads` will be used to transform it in a `dict` again. 

### Memory Storage

For txs, memory storage is available, especially for test purposes. We will also give this option for events. The storage will be simply a `Dict`, where the key will be the `event_id` represented in `bytes`, and the value will be the whole object. Then, we will provide methods to save and retrieve events, implementing the same interface used by Events RocksDB storage.

To decide which kind of storage to use, we will follow the same mechanism currently implemented (Evaluating the usage of `--memory-storage` flag).

## REST API

This endpoint will be provided: 

`GET /event?last_ack_event_id=:last_ack_event_id&size=:size`

Parameters:

- `last_ack_event_id` - The last `event_id` received in the previous request. If not provided, first entry will be retrieved.
- `size` - Number of events that the client wants to receive in the same response. Default is 100. Limit is 1000.

Response:

The response will be an array with `event` objects. This is an example:

```
[
   {
      "id": 1,
      "peer_id": "ecb8edcce0a34cb791923188cb3f18fd",
      "timestamp": 1658868080,
      "type": 2,
      "group_id": 1,
      "data": {
         ...
   }
]
```

Error:

- If `last_ack_event_id` is an event that does not exist (Example: Last `event_id` on database is 1000, but client pass 2000 as `last_received`, the API will return `404 - Not Found`.
- If client pass a `size` <= 1 or > 1000, the API will return `400 - Bad Request`, informing that size is out of range.

## WebSocket communication

Messages will have a sequential `event_id` starting from 0, it is the client's responsibility to store the last event received. In case a connection dies, the new connection will not know where it stopped, so the client has pass that information to the server.

#### - Start Stream Request

Tell WebSocket to start streaming events from a certain `event_id`.

#### Direction

Client -> Server

#### Message Body

| Field | Type | Description |
|------|------|-------------|
| `type` | `Literal['START_STREAM']` | The message type. |
| `last_ack_event_id` | `Optional[NonNegativeInt]` | The last `event_id` the client has received, so the stream starts from the event after that one. `None` if the client wants to receive from the first event. |
| `window_size` | `NonNegativeInt` | The number of events the client is able to process before acknowledging that it received some event. |

#### - Stop Stream Request

Tell WebSocket to stop streaming events.

#### Direction

Client -> Server

#### Message Body

| Field | Type | Description |
|------|------|-------------|
| `type` | `Literal['STOP_STREAM']` | The message type. |

#### - ACK Request

Tell WebSocket that the client acknowledges that it receive a certain `event_id`. Also used to control the flow of events via the `window_size` field.

#### Direction

Client -> Server

#### Message Body

| Field | Type | Description |
|------|------|-------------|
| `type` | `Literal['ACK']` | The message type. |
| `ack_event_id` | `NonNegativeInt` | The last `event_id` the client has received, so the available window is calculated from that one. |
| `window_size` | `NonNegativeInt` | The number of events the client is able to process before acknowledging another event. |

#### - Event Response

Event data the Server sends to the Client.

#### Direction

Server -> Client

#### Message Body

| Field | Type | Description |
|------|------|-------------|
| `type` | `Literal['EVENT']` | The message type. |
| `event` | `BaseEvent` | The event data as described above. |
| `latest_event_id` | `NonNegativeInt` | The ID of the last event the server has processed. Useful for the Client to know how far it is from real time events. |

#### - Invalid Request Response

Error message the Server sends to the Client when the Client has performed an invalid request.

#### Direction

Server -> Client

#### Message Body

| Field | Type | Description |
|------|------|-------------|
| `type` | `InvalidRequestType` | The message type. Options described below. |
| `invalid_request` | `Optional[str]` | The request that was invalid, or `None` if there was no request (read the `EVENT_WS_NOT_RUNNING` option below). |
| `error_message` | `Optional[str]` | A human-readable description of why the request was invalid. |

Here are the possible values of the `InvalidRequestType` enum type:

- `EVENT_WS_NOT_RUNNING`: Sent when the Client connection opens to the WebSocket Server, but the server has not yet been started. The `invalid_request` field on the response is empty.
- `STREAM_IS_ACTIVE`: Sent when the Client tries to start a stream that is already started.
- `STREAM_IS_INACTIVE`: Sent when the Client tries to either send an ACK or stop message to a stream that is already stopped.
- `VALIDATION_ERROR`: Sent when the Client tries to send a request with a malformed body.
- `ACK_TOO_SMALL`: Sent when the Client tries to send a ACK `event_id` that is smaller than the last ACK `event_id` it has sent.
- `ACK_TOO_LARGE`: Sent when the Client tries to send a ACK `event_id` that is larger than the last event the Server has sent.

## Testing Scenarios

For testing purposes, we will provide a separate Python application that will simulate a sequence of events. The user will be able to start this application via command line, passing one of the three initially available scenarios: `SINGLE_CHAIN`, `BEST_CHAIN_WITH_SIDE_CHAINS`, or `MULTIPLE_FORKS`.

Example: `./events_simulator.py --scenario SINGLE_CHAIN`

A websocket server will be started and will wait connections from clients (following the same structure of the original websocket). Once requested (passing the `start_streaming_events` message), the events will be sent to the client. This way, the user do not need to run a full node to test the application.

A detailed document to instruct users on how to run the tests will be built as part of this task.

## Final Task Breakdown

No changes from the task breakdown of the [high level design](https://github.com/HathorNetwork/hathor-core/issues/405).

**Comment by lucas3003** [comment]
First version finished. Reviewers: @msbrogli @pedroferreira1

**Comment by msbrogli** [comment]
Hi @lucas3003 . Thanks for the low-level design. Here are my thoughts and questions:

> By default, events on this scenario will be captured unless the user provides the --skip-load-events flag.

1. Why would we emit these events? Haven't they been emitted before? I feel the most natural behavior would be to just skip them unless the user requests (and I'm not sure in which case it would be useful. Any suggestions?)

2. What happens if the user does not enable RocksDB Storage? Would you create your own RocksDB? Would you have a memory storage for events? Or would you disable the event system? We usually use the memory storage for testing purposes.

3. Rest API: What is the response format?

4. Testing Scenarios: A suggestion would be to create some testing databases with marks (e.g., a reorg occurs on event_id=4231). So developers can run their full nodes using these databases to run integration tests. I haven't given much thought for this suggestion. Feel free to skip it :)

Note: Nice diagram for the consensus algorithm.

**Comment by lucas3003** [comment]
Thanks for the comments @msbrogli. Here are the answers:

> Why would we emit these events? Haven't they been emitted before? I feel the most natural behavior would be to just skip them unless the user requests (and I'm not sure in which case it would be useful. Any suggestions?)

I thought on a use case where the user downloads a snapshot to speed-up the initialization and want to maintain a database (Like Wallet Service) with all txs. Do you think this would be a feasible

> What happens if the user does not enable RocksDB Storage? Would you create your own RocksDB? Would you have a memory storage for events? Or would you disable the event system? We usually use the memory storage for testing purposes.

Good point. I hadn’t thought about a memory storage. I will include it because I think it makes sense for testing purposes.

> Rest API: What is the response format?

Good point. I will include the response format in the design.

> Testing Scenarios: A suggestion would be to create some testing databases with marks (e.g., a reorg occurs on event_id=4231). So developers can run their full nodes using these databases to run integration tests. I haven't given much thought for this suggestion. Feel free to skip it :)

I liked the idea. Would it be kind of a big JSON with all events and a different structure indicating where reorg started, for example?

**Comment by jansegre** [comment]
> > Why would we emit these events? Haven't they been emitted before? I feel the most natural behavior would be to just skip them unless the user requests (and I'm not sure in which case it would be useful. Any suggestions?)
> 
> I thought on a use case where the user downloads a snapshot to speed-up the initialization and want to maintain a database (Like Wallet Service) with all txs. Do you think this would be a feasible

I also had the same impression that `--skip-load-events` may not be a good flag. I was going to suggest reversing it to `--emit-load-events`, but maybe there's a better alternative. If there is a way to know which events have already been emitted, this could be used instead of a flag to decide whether to skip/not skip emitting loading events, a snapshot would not have the record of any events being emitted (and we will have to make sure of that when creating snapshots) so when the node starts it will see that no events have ever been emitted and would start emitting them from the start.

Does this make sense?

In the end I think the less choices the user has to make the better. In the case of the flag proposed, it looks like the user might not want to skip load events on the first run, but would want to skip load events on later runs, I'm not sure what errors this could lead if any to but it seems like something very easy to do by mistake.

> > What happens if the user does not enable RocksDB Storage? Would you create your own RocksDB? Would you have a memory storage for events? Or would you disable the event system? We usually use the memory storage for testing purposes.
> 
> Good point. I hadn’t thought about a memory storage. I included on the design because I think it makes sense for testing purposes.

Maybe it would make sense to require a RocksDB storage for using the event queue.

Other than that this design looks good to me.

**Comment by luislhl** [comment]
> a snapshot would not have the record of any events being emitted (and we will have to make sure of that when creating snapshots)

Is this possible to do? If so, how?

Maybe this should be considered in the design as well. Currently to create snapshots we simply zip the whole `data` folder.

I think this issue also connects with https://github.com/HathorNetwork/ops-tools/issues/426, where we want to monitor the storage size of the blockchain. If we will store events in RocksDB, they would need to be ignored in this monitoring. But it seems this doesn't affect decisions here, only in the other issue.

**Comment by lucas3003** [comment]
> I also had the same impression that --skip-load-events may not be a good flag. I was going to suggest reversing it to --emit-load-events, but maybe there's a better alternative. If there is a way to know which events have already been emitted, this could be used instead of a flag to decide whether to skip/not skip emitting loading events, a snapshot would not have the record of any events being emitted (and we will have to make sure of that when creating snapshots) so when the node starts it will see that no events have ever been emitted and would start emitting them from the start.

It does make sense! We will emit `LOAD_STARTED` and `LOAD_FINISHED` events. We can check if these events were triggered and then skip events during LOAD phase. What do you think? 

> Maybe it would make sense to require a RocksDB storage for using the event queue.

I think it is easy to also implement an in-memory storage (Simply a Dict of events). But I do not know how widely used this would be.

**Comment by lucas3003** [comment]
> Is this possible to do? If so, how?
> 
> Maybe this should be considered in the design as well. Currently to create snapshots we simply zip the whole data folder.

I think this can be done if we implement event as a separate database. Then, a `data_event.db` folder inside `data` would be created, and to create a snapshot, we would simply ignore that. This is easy to implement.

**Comment by jansegre** [comment]
> > I also had the same impression that --skip-load-events may not be a good flag. I was going to suggest reversing it to --emit-load-events, but maybe there's a better alternative. If there is a way to know which events have already been emitted, this could be used instead of a flag to decide whether to skip/not skip emitting loading events, a snapshot would not have the record of any events being emitted (and we will have to make sure of that when creating snapshots) so when the node starts it will see that no events have ever been emitted and would start emitting them from the start.
> 
> It does make sense! We will emit `LOAD_STARTED` and `LOAD_FINISHED` events. We can check if these events were triggered and then skip events during LOAD phase. What do you think?

I think that makes sense, finding these specific events seems relevant, so we don't have to make a `O(n)` scan for example. I think that shouldn't be too hard to include in the design.

> > Maybe it would make sense to require a RocksDB storage for using the event queue.
> 
> I think it is easy to also implement an in-memory storage (Simply a Dict of events). But I do not know how widely used this would be.

That's fine, but my concern was more about the consistency of behavior when using events stored in RocksDB, vs events stored in Memory, specifically in regards to skipping the events when loading. If were to be possible for a RocksDB storage to be used with Memory stored events, there would be a strange behavior where we never know the load events were emitted. I think this is covered by this design when we choose the storage engine based on the same flag that we use to choose the transactions storage.

> I think this issue also connects with [HathorNetwork/ops-tools#426](https://github.com/HathorNetwork/ops-tools/issues/426), where we want to monitor the storage size of the blockchain. If we will store events in RocksDB, they would need to be ignored in this monitoring. But it seems this doesn't affect decisions here, only in the other issue.

I think this falls on the same case as the indexes. Since indexes aren't _technically_ part of the blockchain. But I think the point of the ops-tools design is a little more broad to know how the node is using the storage, so measuring the storage of events would just have its own classification, like indexes would be measured separately.

**Comment by lucas3003** [comment]
> I think that makes sense, finding these specific events seems relevant, so we don't have to make a O(n) scan for example. I think that a consideration for that should be included in the design.

It is actually O(n) because we store the `event_id` as key. To overcome this problem, I added a new column family, called `metadata`, where we will store `LOAD` if the node is loading the local database or `SYNC` if `LOAD` state has passed and the node is receiving and sending data through the network. Then, we will use O(1) to get the information.

**Comment by msbrogli** [comment]
Approved for me.

**Comment by jansegre** [comment]
Approved for me too.

**Comment by glevco** [comment]
_This design has been moved and updated [here](https://github.com/HathorNetwork/rfcs/blob/master/projects/reliable-integration/0002-low-level-design.md)._
