### ISSUE TITLE
feat: improve logging system

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-core#5]
When deploying using Docker, we need to limit the size of the log file. Usually, it is solved using log rotate. In this case, maybe we will have to make our full-node reopen the log files after a signal.

Which signal will we use to reopen the log files? HUP? USR1?

This issue was found because we got out of disk space in our full-nodes of testnet-bravo. After truncating the log files, everything worked properly.

**Comment by obiyankenobi** [comment]
We can use Docker's log rotation: https://docs.docker.com/config/containers/logging/configure/

I imagine anyone running a full-node will have some kind of manager. If not Docker, maybe supervisorctl, which also has a way of rotating the logs. In that sense, I don't think we need to have this on the full-node.

**Comment by obiyankenobi** [comment]
As discussed on Slack, will move this back to backlog and we'll prioritize again on next meeting. For now, we've agreed on fixing the problem of the docker log growing indefinitely (I've opened a bug for this on aws-deploy-tools repo).

This issue will track a more comprehensive refactor/enhancement on our log system. Updated the title accordingly.

**Comment by jansegre** [comment]
Our container image doesn't really log to any files inside the container (except for the internal rocksdb logs, which do their own rotation). Instead we log to stdout and this is managed externally and independently from the fullnode. While we can certainly add support for different logging structures, we don't officially support other deploy schemes.

I'd say it's better to reconsider this only after we officially support other methods and the actual need for this arises.
