### ISSUE TITLE
feat(mining): Get HTR and BTC addresses from Stratum login

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-core#50]
It makes a public solo mining server possible.

MR: https://gitlab.com/HathorNetwork/hathor-python/merge_requests/363

Another related MR: https://gitlab.com/HathorNetwork/hathor-python/merge_requests/370

**Comment by jansegre** [comment]
Another related MR: https://gitlab.com/HathorNetwork/hathor-python/merge_requests/370
