### ISSUE TITLE
[Design] feat(wallet): New API to improve wallet loading time

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-core#54]
# Problem

The wallet loading time may be high when there are too many transactions.

# Proposed Solution

## New API: `getAddressPaginatedHistory`

The new API would receive a list of addresses and return something like this:

```es6
{
  HTR: {
    _token: { name, symbol, tokenUid },
    [addr1]: { balance, has_more, history, history_count, utxo_list },
    [addr2]: { balance, has_more, history, history_count, utxo_list },
    [addr3]: { balance, has_more, history, history_count, utxo_list },
  },
  [token1]: {
    [addr1]: { balance, has_more, history, history_count, utxo_list },
    [addr2]: { balance, has_more, history, history_count, utxo_list },
    [addr3]: { balance, has_more, history, history_count, utxo_list },
  },
}
```

- `balance`: an integer with the balance of the address for that token.
- `has_more`: a bool that is true if there are more items in the history.
- `history`: list of transactions sorted by descending timestamp.
- `history_count`: an integer with the total number of transactions.
- `utxo_list`: a list of utxo in the format `{ tx_id, index, is_authority, value }`.

**To discuss:** The `utxo_list` may be long. Do we need to load all utxo? Maybe we do. In the wallet, we can detect "too many utxo" and suggest a compression during the load. If the user authorizes, the wallet can generate one transaction every 255 utxos, and speed up the next load.

**To discuss:** Do we have to return all tokens? Or can we require a list of tokens as well? In the Desktop Wallet, we show a list of unregistered tokens.

**To do:** Paginated `utxo_list`. Maybe we should create a new resource for UTXO because of its pagination.

## Impact on Wallet

The solution must detail how the wallet will perform the following things:

1. Calculate the balance per token
2. List the transaction history per token
3. Send transactions
4. Create tokens
5. Use authority outputs
6. List "unregistered tokens"

### Calculate the balance per token

The balance of the wallet is equal to the sum of the balances of its addresses. The balance of each address is equal to the sum of the value of its utxos.

### List the transaction history per token

The wallet can concatenate the history of the addresses and sort by decreasing timestamp. This sorted list will be presented to the user. When the user goes to the next page, the wallet can keep showing the transactions until the last page. In the last page, the wallet must load more data from server.

The total number of transaction is the sum of `history_count` of the addresses.

### Send transactions

As all utxos have been loaded, we can send transactions just like we do now.

### Create tokens

Create tokens is not affected.

### Use authority outputs

As all utxos have been loaded, we can perform any operation with the authority outputs. But we won't have the full list of authority outputs that have already been spent.

### List "unregistered tokens"

It depends if the API returns all tokens or only the tokens requested by the wallet.

> **TODO**: Need more details after an initial discussion.

## API Implementation Details

> **TODO**: Discuss how we can implement it in a reasonable time and space complexity. We can also discuss how we can hold a cache in memory but store the data structure on disk.

# Alternative solutions

We can send the xpub to the API, and it can return all necessary pieces of information in one response. The advantage is that the wallet would load in a single request. The disadvantage is that it will only work for HD Wallets, and we cannot use Bloom Filters to improve user's privacy.

**Comment by msbrogli** [comment]
@pedroferreira1 @jansegre @obiyankenobi Should Can you share your thoughts, please? Maybe I should move it to an RFC.

**Comment by pedroferreira1** [comment]
I like this approach because the user can start using the wallet much faster than nowadays. My only concern is about the `utxo_list` because it's the main reason some wallets are not loading right now. It would return thousands of utxos and would take too long. So for this solution to work, we would need to do an async/lazy load of those utxos. In that case it would be necessary to change the send tokens and create tokens screen to validate if all utxos have been loaded already.

I feel it's a big refactor to be done on the wallet and, even thought there are clear benefits, I wouldn't consider this a priority, since the wallet is loading correctly nowadays.

One other note is about the `utxo_list` element. It also needs the `token_uid` on it.

**Comment by obiyankenobi** [comment]
Let me see if I understood the basic idea: the `history` element on the response would be paginated? So we'd return, let's say, at most 50 at a time, ordered by timestamp? And if the user goes to the last page he'd have to call `getAddressPagedHistory` again to get the next transactions?

For this to make a difference now, we need to implement the "too many utxo" compression. Very few people have that many transactions in history (right now, this will change in the future). The only ones who do are miners, who also have a lot of utxos (like the user who had problems recently), so we'd need to load all of them.

**Comment by msbrogli** [comment]
> I like this approach because the user can start using the wallet much faster than nowadays. My only concern is about the `utxo_list` because it's the main reason some wallets are not loading right now. It would return thousands of utxos and would take too long. So for this solution to work, we would need to do an async/lazy load of those utxos. In that case it would be necessary to change the send tokens and create tokens screen to validate if all utxos have been loaded already.

I think the wallet should always load all utxos. Storing a partial list of utxos would be hard because we get the utxo using an address list. It would be faster if we change to get the utxo using the xpub.

> I feel it's a big refactor to be done on the wallet and, even thought there are clear benefits, I wouldn't consider this a priority, since the wallet is loading correctly nowadays.

I don't think it would be a big refactor after the refactor of the lib. But I think we should discuss it further before moving to the code.
 
> One other note is about the `utxo_list` element. It also needs the `token_uid` on it.

I think it doesn't because they are grouped by token.

**Comment by msbrogli** [comment]
> Let me see if I understood the basic idea: the `history` element on the response would be paginated? So we'd return, let's say, at most 50 at a time, ordered by timestamp? And if the user goes to the last page he'd have to call `getAddressPagedHistory` again to get the next transactions?

Exactly. The user wouldn't be able to go to the last page, but they may go to the next page.

> For this to make a difference now, we need to implement the "too many utxo" compression. Very few people have that many transactions in history (right now, this will change in the future). The only ones who do are miners, who also have a lot of utxos (like the user who had problems recently), so we'd need to load all of them.

Maybe we should discuss the utxo compression in an issue in the hathor-wallet-lib. It would be a first step towards this refactor.

**Comment by jansegre** [comment]
Bikeshed: I don't know if "Paged" is good, at least it sounds weird. I think "Paginated" is the usual term.

**Comment by msbrogli** [comment]
> Bikeshed: I don't know if "Paged" is good, at least it sounds weird. I think "Paginated" is the usual term.

Fixed. Thanks!

**Comment by msbrogli** [comment]
I just created this issue to discuss UTXOs Compression: https://github.com/HathorNetwork/hathor-wallet-lib/issues/58

**Comment by obiyankenobi** [comment]
Per our discussion in the UTXO consolidation issue, it might make sense to separate the address history and utxo in 2 different APIs. That would make it easier for the wallet to detect utxo consolidation is needed and it shouldn't impact the address history.

**Comment by pedroferreira1** [comment]
Approved

**Comment by jansegre** [comment]
I'm on board with this too.

**Comment by Aimeelu668** [comment]
我们对接优盾钱包的，像交易所这样的系统可以通过API快速的实现BTC\ETH等币的充提，私钥不存服务器上，平台自己通过客户端管理，提供归集、分花、代付、统计等操作，安全方便。

**Comment by msbrogli** [comment]
We decided to move forward with a different approach. Instead of developing a new API to improve wallet loading time, we will develop a whole new service to do it. The design of the service will be discussed in [this issue](https://github.com/HathorNetwork/hathor-wallet-service/issues/1).
