### ISSUE TITLE
fix(mergedmining): MiningRigRentals is showing a significantly higher hash rate than the correct value

### ISSUE THREAD

**Issue by jansegre** [HathorNetwork/hathor-core#57]
It appears to be related to the difficulty estimator. Probably implementing a proper estimator would fix this.

MR: https://gitlab.com/HathorNetwork/hathor-python/merge_requests/370

**Comment by jansegre** [comment]
This: https://gitlab.com/HathorNetwork/hathor-python/merge_requests/370 has the fixes that address this issue.

**Comment by obiyankenobi** [comment]
Isn't the code from MR 370 already running on our beta coordinator?

**Comment by jansegre** [comment]
This has been fixed a while ago already.
