### ISSUE TITLE
tests(p2p): Add tests for Downloader when some requests take too long and timeout

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-core#65]
Some requests took too long, and it caused the sync to randomly stop. We did this hot fix but we need to test it (and maybe make it even more robust).

MR: https://gitlab.com/HathorNetwork/hathor-python/-/merge_requests/375

**Comment by jansegre** [comment]
The Downloader is no longer in active use and will be removed along sync-v1 soon.
