### ISSUE TITLE
fix: Save metadata of genesis

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-core#72]
Current version does not save metadata for genesis because it is not necessary when the full node is running. So, if we shutdown the full node and try to simply load the transactions from the storage, only the metadata of the genesis will be incorrect; while all other metadata will be correct.

So saving the metadata of genesis will allow us to correctly load the transactions from the storage without processing all transactions.

MR: https://gitlab.com/HathorNetwork/hathor-python/-/merge_requests/385

## Test To Do

- [x] Sync a new node using a persistent storage
- [x] Start a full node that already has transactions in the storage

**Comment by msbrogli** [comment]
Saving the metadata is not easy because some backends store both the tx and the metadata in the same file. In this case, I would have to save only the metadata and handle this condition in many parts of the code. A simpler solution would be to save the genesis in the storage, including its metadata. I'd also include a safety check that the stored genesis is the same as the expected genesis. What do you think? @jansegre @obiyankenobi @pedroferreira1

**Comment by obiyankenobi** [comment]
We can go for this solution.

**Comment by pedroferreira1** [comment]
Good to me
