### ISSUE TITLE
Improve sync-v2's `deferred_by_key` implementation

### ISSUE THREAD

**Issue by glevco** [HathorNetwork/hathor-core#726]
We might refactor it in the future, but not sure what's the best solution for this case. For now, we will create one constant per key used by `self.deferred_by_key`.

_Originally posted by @msbrogli in https://github.com/HathorNetwork/hathor-core/pull/275#discussion_r1274143232_

**Comment by jansegre** [comment]
We don't use `defferred_by_key` anymore in sync-v2's implementation.
