### ISSUE TITLE
Pubsub event WALLET_ADDRESS_HISTORY is sent multiple times

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-core#73]
When a new tx arrives in the wallet, it should receive a new tx event and an update for the txs that were spent.

However we are currently receiving 4 events for the new tx and some duplicate events for the other txs also. Besides that, when we open a Transaction Detail screen we are also receiving two events of this.

I think there is a metadata update that is wrongly triggering this event publish but still needs further investigation. The line code that should handle this is in this method but is probably not working (hathor/indexes.py)

```
423     def handle_tx_event(self, key: HathorEvents, args: 'EventArguments') -> None:
424         """ This method is called when pubsub publishes an event that we subscribed
425         """
426         data = args.__dict__
427         tx = data['tx']
428         meta = tx.get_metadata()
429         if meta.has_voided_by_changed_since_last_call() or meta.has_spent_by_changed_since_last_call():
430             self.publish_tx(tx)
```

This issue is causing some freezing when using the wallet with many transactions and it's described on https://github.com/HathorNetwork/hathor-wallet/issues/96.

**Comment by jansegre** [comment]
This should not be the case anymore, either way the "reliable events" should eventually replace the "pubsub events".
