### ISSUE TITLE
Several seconds taken to log the receival of `BLOCKS-END` in sync-v2

### ISSUE THREAD

**Issue by luislhl** [HathorNetwork/hathor-core#731]
It seems the peer frequently takes several seconds (sometimes more, sometimes less) between sending the last block in the stream and sending this `BLOCKS-END` message.

In theory, the `BLOCKS-END` should be sent by the peer immediately after the last block in the stream, so taking several seconds between these 2 events being logged in the receiving peer looks odd.

It's not clear whether this is normal behavior or not, so we should investigate to be sure.

If we can get rid of these wait times, this would make a big different in the total time of a full sync.

Some screenshots I've collected to show the problem:

![Screenshot from 2023-07-24 12-05-20](https://user-images.githubusercontent.com/5041650/256338953-4f710a47-0c6f-41d0-91db-2764cddbbece.png)
![Screenshot from 2023-07-24 12-05-39](https://user-images.githubusercontent.com/5041650/256338968-23324385-0f8f-4c24-92d8-a158ee5ad623.png)
![Screenshot from 2023-07-24 12-06-16](https://user-images.githubusercontent.com/5041650/256338974-895bface-1249-415a-ae03-08d1641eade2.png)
![Screenshot from 2023-07-24 12-09-22](https://user-images.githubusercontent.com/5041650/256338980-21ea9812-c14a-4b64-8528-b6ef07d84314.png)

_Originally posted by @luislhl in https://github.com/HathorNetwork/hathor-core/pull/275#discussion_r1272654861_

**Comment by 1000cm** [comment]
I got message "remote error" , how? Could you help me?

![hathor](https://github.com/HathorNetwork/hathor-core/assets/118546625/30216aac-6ba9-4245-92d7-02502d3e6582)

**Comment by jansegre** [comment]
This was most likely using an older sync-v2 implementation. This pauses should not occur anymore, if they still happen this issue can be re-opened or a new one created.
