### ISSUE TITLE
Increase rate limit for address_history API endpoint

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-core#74]
We've recently updated the `address_history` API endpoint to paginate the results, so it doesn't take too long to reply a request. This prevents any wallet from having a timeout in one of the load requests when there are many transactions to be loaded. However, this change increases the number of requests executed when loading a wallet and we currently limit on 3r/s in the same IP with burst of 10. If the request is executed fast enough, this might be bad for the user, who could start receiving a lot of 429 status code (rate limit exceeded).

There should be a study about the time it's taking for a request to be executed and if this could really be a problem. If the requests are returning too fast, we could increase the number of transactions allowed in a page (currently we return at most 50 txs in each request) and also we could increase the rate limit.

**Comment by pedroferreira1** [comment]
**Current situation:**

**Maximum txs returned:** 50

**Nginx restriction per-ip:** 
```
{
    'rate': '3r/s',
    'burst': 10,
    'delay': 3
}
```

Tests to know how long does it take to execute each request.

**Normal internet**, i.e. Download 50 Mb/s, ~300ms each full request (with 50 txs)
![image](https://user-images.githubusercontent.com/3298774/79167197-4e0d3200-7dbd-11ea-882f-d040e62950fb.png)

**Fast 3G**, i.e. Download 1500 kb/s = 1.5 Mb/s, Latency = 550 ms (from https://stackoverflow.com/a/48682519/2117670), ~900ms each full request (with 50 txs)
![image](https://user-images.githubusercontent.com/3298774/79167274-7eed6700-7dbd-11ea-9af0-685cc1ef3552.png)

**Slow 3G**, i.e. Download 376 kb/s, Latency 2000 ms (from https://stackoverflow.com/a/48682519/2117670), ~3s each full request (with 50 txs)
![image](https://user-images.githubusercontent.com/3298774/79166973-b4de1b80-7dbc-11ea-813e-5eb821d15626.png)

This problem might happen with people loading a wallet with many transactions in the same address (mostly miners).

**New configuration suggestion:**

**Maximum txs returned:** 150

**Nginx restriction per-ip:** 
```
{
    'rate': '6r/s',
    'burst': 15,
    'delay': 3
}
```

**Comment by msbrogli** [comment]
Seems good to me.
