### ISSUE TITLE
Spike: Speed-up initialization

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-core#79]
MR: https://gitlab.com/HathorNetwork/hathor-python/-/merge_requests/399

**Comment by pedroferreira1** [comment]
I've done a first test and checked that most of the initialization time is wasted on calculating block difficulty (to validate if the new block is valid). See profiler attached.

[initializing.prof.dot.pdf](https://github.com/HathorNetwork/hathor-core/files/4588983/initializing.prof.dot.pdf)

Using `--cache --cache-size 100000` in the run command already helped to increase the average from 16 txs/s to 98 txs/s, so I guess it's not so urgent to investigate this issue.

**Comment by pedroferreira1** [comment]
As described in the previous comment, one of the problems that slows the initialization is getting the block parent from the storage without a cache.

I've done some tests in 2 different notebooks:

1. MacbookPro mid 2012 - 2,5 GHz Intel Core i5
2. MacbookPro 2016 - 2 GHz Intel Core i5

**Tests:**

a) `dev` code without cache

1. 18 txs/s
2. 29 txs/s

**Profiler:** [initialization_no_cache.pdf](https://github.com/HathorNetwork/hathor-core/files/4619266/initialization_no_cache.pdf)

**Main problem:** 
Calling `get_block_parent` on `calculate_block_difficulty` when verifying blocks.

b) `dev` code with cache

1. 110 txs/s
2. 180 txs/s

**Profiler:** [initialization_with_cache.pdf](https://github.com/HathorNetwork/hathor-core/files/4619269/initialization_with_cache.pdf)

**Main problem:**
Calling `_get_lock` for each `get_transaction` when verifying all txs.

c) The lock is useful when executing concurrent access on storage, that is done only by API calls. There is no need to use the lock until the peer is ready, so I removed the lock until it gets ready.

1. 210 txs/s
2. 275 txs/s

**Profiler:** [initialization_new_code_with_cache.pdf](https://github.com/HathorNetwork/hathor-core/files/4619279/initialization_new_code_with_cache.pdf)

**Main problem:**
To be honest with this last change I don't see a big problem in any part of the code, it looks distributed and the most expensive part is saving into cache and getting from cache. I've done some other experiments to improve the speed but none of them had a big difference on performance.

What are your thoughts about this? Should I continue looking into this problem? @obiyankenobi @jansegre @msbrogli

**Comment by msbrogli** [comment]
@pedroferreira1 Even though it has improved a lot, it seems too slow. It would take around 22 minutes to start a full node with 360k txs/blocks. It is better than syncing but I feel it is still too slow.

Here is an idea: What if we skip the consensus validation part and the metadata update, so we would only update the indexes.

**Comment by obiyankenobi** [comment]
I would test @msbrogli's suggestion. If it helps, great. If not, we might not want to spend more time in this issue. Doesn't seem very urgent, but we can debate.

**Comment by pedroferreira1** [comment]
I've done some more changes:

- Followed @msbrogli suggestion and removed the consensus and metadata code while node is not ready. For the final code I won't completely remove it but will execute only for the last blocks and txs;
- Removed the deprecated decorator from the code (this was slowing the process on 8%);
- Removed an unnecessary save to weakref.

Test result:

1. 310 txs/s
2. 410 txs/s

**Profiler:** 
[initializing.prof.dot.pdf](https://github.com/HathorNetwork/hathor-core/files/4629481/initializing.prof.dot.pdf)

~63% of the time is calculating block difficulty. A refactor could be done to increase the speed of it but this is a more complex matter, in my opinion and should have a spike for it.

What are your thoughts? About removing the decorator and the code for consensus and metadata? @msbrogli @obiyankenobi @jansegre

**Comment by obiyankenobi** [comment]
I'm not sure which decorator you're referring to, I need to see the code when the PR is open.

Removing consensus from startup doesn't seem to be a problem.

I'm ok with these results. I think we can move on and come back to this later if we want to speed up even more.

**Comment by jansegre** [comment]
I like this a lot. This has bothered me for a long time, I don't think it is as fast as it could be (because I think it startup can be `O(1)`), but it's very good for now.

I've even tested adding a `--skip-validation` param, which I can add to the current branch for this. Which we can discuss the defaults (maybe `--dont-skip-validation`, or `--validate-last-n-blocks`).

However, I've had some problems syncing after initializing with a lot of transactions, which should be investigated.
