### ISSUE TITLE
Automatically build Docker images

### ISSUE THREAD

**Issue by jansegre** [HathorNetwork/hathor-core#85]
This has been [partially done already](https://hub.docker.com/repository/docker/hathornetwork/hathor-core/builds). Issue for tracking the progress on this. There is a branch from a while ago for [doing this on GitLab CI](https://gitlab.com/HathorNetwork/hathor-python/-/merge_requests/281), but this doesn't apply anymore.

**Comment by jansegre** [comment]
Currently, DockerHub is configured to build `master` branch and tag it `latest` and `dev` branch and tag it `dev`.

What do you think? @obiyankenobi @msbrogli @pedroferreira1

**Comment by obiyankenobi** [comment]
Sounds good to me.

**Comment by jansegre** [comment]
Not sure why I haven't closed this before. But we've been building Docker images automatically for a while now.
