### ISSUE TITLE
Merkle path limit seems to not be enough for BTC blocks due to recent changes

### ISSUE THREAD

**Issue by jansegre** [HathorNetwork/hathor-core#878]
Some miners have reported that BTC blocks could now have more than 4096 transactions, which means that the merkle path to the coinbase transaction would have more than 12 hashes, which is the current hard limit for blocks merged mined with HTR blocks as accepted by `hathor-core`.

We have the `feature-activation` mechanism implemented and being tested on the testnet which in theory should have everything we need to implement a hardfork upgrade at a set block height to make this upgrade smooth. But this is still needs a lot of care in order to avoid accidentally slitting the network.

Just to add some info, here are the [recent blocks in BTC](https://blockstream.info/blocks/recent) (live), some example blocks that have more than 4096 transactions:

- [block at height 817856 has 4529 transactions](https://blockstream.info/block/00000000000000000002223aa019d2f583a0f5ecd00452cb01622c3aaba9240c)
- [block at height 817854 has 4398 transactions](https://blockstream.info/block/00000000000000000001a6a24eb27f1882b7f07c00394ef1732c6e41269c302a)
- [block at height 817853 has 4417 transactions](https://blockstream.info/block/000000000000000000020a08475c21564180ef78638426a1b75eb5d60804590b)
- [block at height 817850 has 5688 transactions](https://blockstream.info/block/000000000000000000025c5ec27a37083999f06cf20707cd4bc4357f8a53f341)

**Comment by glevco** [comment]
Closing this as the update has been activated on mainnet and the problem has been solved.
