### ISSUE TITLE
[Merkle path update] Test Merged Mining with dummy chain on testnet

### ISSUE THREAD

**Issue by glevco** [HathorNetwork/hathor-core#936]
We should implement a way of creating merge mined blocks on testnet with some dummy blockchain, in order to test the maximum Merkle path length update, implemented in this PR: https://github.com/HathorNetwork/hathor-core/pull/910.

According to Feature Activation, the process should start around Sunday, Feb. 4th, meaning that it will reach `LOCKED_IN` around Feb. 11th and will be `ACTIVE` around Feb. 18th. Then:

**Before the feature is activated**

- [x] We should push a merge mined block with a merkle path length of **12 or less**, and assert that it is correctly **accepted** by the network.
- [ ] We should push a merge mined block with a merkle path length of **13 or more**, and assert that it is correctly **rejected** by the network.

**After the feature is activated**

- [x] We should push a merge mined block with a merkle path length of **20**, and assert that it is correctly **accepted** by the network.
- [x] We should push a merge mined block with a merkle path length of **21 or more**, and assert that it is correctly **rejected** by the network.

**Comment by jansegre** [comment]
PR #966 introduces the change to be able to test this.

**Comment by jansegre** [comment]
Blocks mined so far:

- With merkle path 13: https://explorer.testnet.hathor.network/transaction/00000000006d3c0b43a2493e50e57a8db28438de6df831c1fb647740aeae9cd8
- 

It's been slow since I'm using a cpuminer, but at least I've got a block with merkle path of len 13.

**Comment by jansegre** [comment]
The last test isn't needed anymore, the upgrade has been successful.
