### ISSUE TITLE
[Design] Ops: Check whether peers have the same consensus

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-core#98]
We will check only the consensus of the blockchain for sync'ed peers. The verification will run every 5 minutes.

We will implement a new command in the p2p protocol called `GET_LATEST_BEST_BLOCKS`. It won't have any parameter and will return a list with the latest `N` blocks in the best blockchain, e.g., `[a, b, c, d, e, f]`.

The value of `N` will be set as `max(10, ceil(2 * P2P_SYNC_THRESHOLD / AVG_TIME_BETWEEN_BLOCKS))`. For the current mainnet settings, `P2P_SYNC_THRESHOLD = 60` and `AVG_TIME_BETWEEN_BLOCKS = 30`, so `N` will be equal to 10.

It is important to send a bunch of blocks, so we can log and verify after which block the consensus is different.

After receiving the list of hashes, the full node will verify that `a` exists and is in the best blockchain. Then, it will check that `b` exists, and so on. If any hash exists and is not in the best blockchain, it should mark the connection with `CONSENSUS_WARNING`. If a given hash does not exists, all hashes following it must not exist as well.

The flag `CONSENSUS_WARNING` can be cleared if the verification is ok.

We must add a counter of the number of connections with `CONSENSUS_WARNING` in Promotheus. We should also give this information in the peers API.

**Comment by msbrogli** [comment]
We can have one rule for the blockchain and another one for the transactions.

Regarding the blockchain, we can exchange the list of the last `N` (maybe 20?) blocks and find an alignment. For example:

- Peer 1: `[a, b, c, d, e, f, g, h]` (each letter is the tx_id of a block)
- Peer 2: `[d, e, f, g, h, i, j, k]`.

In this case, they would have a misalignment of 3 blocks, which is weird. We can give SUCCESS for up to 2 misaligned blocks, WARNING for 3-5 misaligned blocks, and ERROR for 6+ misaligned blocks.

Regarding the transactions, the basic idea is to compare the tips and their `voided_by` metadata at different timestamps, but we need to dive deep more into it because of the syncing, i.e., the peers are always slightly different even when they are synced. Maybe it is enough to check at `now - P2P_SYNC_THRESHOLD`.

Anyway, we can first implement the blockchain consensus verification. We may include the `consensus_status` in the peers API and a counter of WARNINGS/ERRORS in Grafana, so we can monitor and generate alerts.

What do you think? @obiyankenobi @pedroferreira1 @jansegre

**Comment by obiyankenobi** [comment]
Shouldn't it be enough to just check the blockchain consensus? In the end, all transactions should be confirmed directly/indirectly by a block.

As for the blockchain check, instead of fixed thresholds (N blocks), shouldn't we base on the `P2P_SYNC_THRESHOLD`? So I check if I have the same consensus of a peer, considering `timestamp < latest_timestamp - P2P_SYNC_THRESHOLD`. We might have warnings if they have different blocks in the interval (now, latest_timestamp - P2P_SYNC_THRESHOLD).

**Comment by msbrogli** [comment]
> Shouldn't it be enough to just check the blockchain consensus? In the end, all transactions should be confirmed directly/indirectly by a block.

You're almost right, except for the fact that we can't say the "transactions with no confirmations" are the same. But I agree that, in this case, checking the blocks is enough. Good point!

> As for the blockchain check, instead of fixed thresholds (N blocks), shouldn't we base on the `P2P_SYNC_THRESHOLD`? So I check if I have the same consensus of a peer, considering `timestamp < latest_timestamp - P2P_SYNC_THRESHOLD`. We might have warnings if they have different blocks in the interval (now, latest_timestamp - P2P_SYNC_THRESHOLD).

In this case, we would rely on the interval tree to get those. It seems easier to get the last N blocks, so we can refactor to remove the interval tree of the blocks in the future. But I agree your suggestion would work just fine as well.

**Comment by obiyankenobi** [comment]
But we should get the latest N blocks starting from `latest_timestamp - P2P_SYNC_THRESHOLD` (or `now - P2P_SYNC_THRESHOLD`). Because if we accept that nodes might not be immediately synced in this threshold window, I don't think we should take that into account for consensus.

**Comment by msbrogli** [comment]
I think we should only check whether the consensus is the same when the full nodes are synced. Otherwise, we just skip it. The reason for that is that blocks-to-be-downloaded can change the best blockchain, and we don't know the consensus for a given timestamp, i.e., we just know it for the current timestamp.

**Comment by jansegre** [comment]
Since this should be informational only and not affect any behavior. I think we could experiment with multiple approaches.

Only comparing the last N blocks when a peer is synced (which is the latest proposal, if I got it right). Seems like a great starting point. I see no downsides to starting with that.

**Comment by pedroferreira1** [comment]
> Regarding the blockchain, we can exchange the list of the last N (maybe 20?) blocks and find an alignment.

We are going to check here only the blocks on the best chain, right?

I would go only with the block consensus check for now also.

I was just wondering when we should do this check because if we decide to add to grafana this warnings data, are we doing this every 5 seconds? Maybe we should add a flag to the start to decide if we are doing this check or not, so we don't flood the network with it.

**Comment by msbrogli** [comment]
@pedroferreira1 I think we can add it as a warning in the connection. I think we can do it every 10 minutes. So, if something is wrong, Grafana will receive the data on the next push.

What do you think?

**Comment by pedroferreira1** [comment]
I think it's good. I agree there is no need to check this in an interval smaller than this and this way won't decrease full node performance.

**Comment by obiyankenobi** [comment]
Seems good and simple!

**Comment by jansegre** [comment]
It looks correct. There's no harm if it isn't right?
